/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BatchId = bigint;
export interface CartItem {
  'product_id' : ProductId,
  'quantity' : bigint,
  'actual_sale_price' : number,
}
export interface Category {
  'id' : CategoryId,
  'owner' : UserId,
  'name' : string,
  'description' : string,
}
export type CategoryId = bigint;
export interface CategoryInput { 'name' : string, 'description' : string }
export interface DashboardStats {
  'monthly_profit' : number,
  'total_inventory_value' : number,
  'recent_sales' : Array<Sale>,
  'monthly_volume_points' : number,
}
export interface InventoryBatchPublic {
  'id' : BatchId,
  'quantity_remaining' : bigint,
  'product_id' : ProductId,
  'unit_cost' : number,
  'date_received' : Timestamp,
}
export interface InventoryLevel {
  'product_id' : ProductId,
  'total_qty' : bigint,
  'batches' : Array<InventoryBatchPublic>,
}
export interface MonthlySalesTrend {
  'month_label' : string,
  'total_revenue' : number,
  'total_volume_points' : number,
}
export type POStatus = { 'Received' : null } |
  { 'Pending' : null };
export interface Product {
  'id' : ProductId,
  'mrp' : number,
  'sku' : string,
  'owner' : UserId,
  'name' : string,
  'earn_base' : number,
  'volume_points' : number,
  'hsn_code' : string,
  'category_id' : CategoryId,
}
export type ProductId = bigint;
export interface ProductInput {
  'mrp' : number,
  'sku' : string,
  'name' : string,
  'earn_base' : number,
  'volume_points' : number,
  'hsn_code' : string,
  'category_id' : CategoryId,
}
export interface ProfileInput {
  'business_name' : string,
  'email' : string,
  'business_address' : string,
  'phone_number' : string,
  'fssai_number' : string,
}
export interface PurchaseOrder {
  'id' : PurchaseOrderId,
  'status' : POStatus,
  'owner' : UserId,
  'vendor' : string,
  'timestamp' : Timestamp,
}
export type PurchaseOrderId = bigint;
export interface PurchaseOrderInput {
  'vendor' : string,
  'items' : Array<PurchaseOrderItemInput>,
}
export interface PurchaseOrderItem {
  'product_id' : ProductId,
  'unit_cost' : number,
  'quantity' : bigint,
  'po_id' : PurchaseOrderId,
}
export interface PurchaseOrderItemInput {
  'product_id' : ProductId,
  'unit_cost' : number,
  'quantity' : bigint,
}
export interface Sale {
  'id' : SaleId,
  'owner' : UserId,
  'timestamp' : Timestamp,
  'total_revenue' : number,
  'total_volume_points' : number,
  'total_profit' : number,
}
export type SaleId = bigint;
export interface SaleItem {
  'unit_cost_snapshot' : number,
  'product_id' : ProductId,
  'product_name_snapshot' : string,
  'volume_points_snapshot' : number,
  'quantity' : bigint,
  'actual_sale_price' : number,
  'sale_id' : SaleId,
  'mrp_snapshot' : number,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface _SERVICE {
  'createCategory' : ActorMethod<[CategoryInput], CategoryId>,
  'createProduct' : ActorMethod<[ProductInput], [] | [ProductId]>,
  'createPurchaseOrder' : ActorMethod<[PurchaseOrderInput], PurchaseOrderId>,
  'createSale' : ActorMethod<[Array<CartItem>], [] | [SaleId]>,
  'deleteCategory' : ActorMethod<[CategoryId], boolean>,
  'deleteProduct' : ActorMethod<[ProductId], boolean>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getInventoryBatches' : ActorMethod<[ProductId], Array<InventoryBatchPublic>>,
  'getInventoryLevels' : ActorMethod<[], Array<InventoryLevel>>,
  'getMonthlySalesTrend' : ActorMethod<[], Array<MonthlySalesTrend>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProfile' : ActorMethod<[], [] | [ProfileInput]>,
  'getPurchaseOrderItems' : ActorMethod<
    [PurchaseOrderId],
    Array<PurchaseOrderItem>
  >,
  'getPurchaseOrders' : ActorMethod<[], Array<PurchaseOrder>>,
  'getSale' : ActorMethod<[SaleId], [] | [Sale]>,
  'getSaleItems' : ActorMethod<[SaleId], Array<SaleItem>>,
  'getSales' : ActorMethod<[], Array<Sale>>,
  'markPurchaseOrderReceived' : ActorMethod<[PurchaseOrderId], boolean>,
  'updateCategory' : ActorMethod<[CategoryId, CategoryInput], boolean>,
  'updateProduct' : ActorMethod<[ProductId, ProductInput], boolean>,
  'updateProfile' : ActorMethod<[ProfileInput], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];