/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CategoryInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const CategoryId = IDL.Nat;
export const ProductInput = IDL.Record({
  'mrp' : IDL.Float64,
  'sku' : IDL.Text,
  'name' : IDL.Text,
  'earn_base' : IDL.Float64,
  'volume_points' : IDL.Float64,
  'hsn_code' : IDL.Text,
  'category_id' : CategoryId,
});
export const ProductId = IDL.Nat;
export const PurchaseOrderItemInput = IDL.Record({
  'product_id' : ProductId,
  'unit_cost' : IDL.Float64,
  'quantity' : IDL.Nat,
});
export const PurchaseOrderInput = IDL.Record({
  'vendor' : IDL.Text,
  'items' : IDL.Vec(PurchaseOrderItemInput),
});
export const PurchaseOrderId = IDL.Nat;
export const CartItem = IDL.Record({
  'product_id' : ProductId,
  'quantity' : IDL.Nat,
  'actual_sale_price' : IDL.Float64,
});
export const SaleId = IDL.Nat;
export const UserId = IDL.Principal;
export const Category = IDL.Record({
  'id' : CategoryId,
  'owner' : UserId,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const Sale = IDL.Record({
  'id' : SaleId,
  'owner' : UserId,
  'timestamp' : Timestamp,
  'total_revenue' : IDL.Float64,
  'total_volume_points' : IDL.Float64,
  'total_profit' : IDL.Float64,
});
export const DashboardStats = IDL.Record({
  'monthly_profit' : IDL.Float64,
  'total_inventory_value' : IDL.Float64,
  'recent_sales' : IDL.Vec(Sale),
  'monthly_volume_points' : IDL.Float64,
});
export const BatchId = IDL.Nat;
export const InventoryBatchPublic = IDL.Record({
  'id' : BatchId,
  'quantity_remaining' : IDL.Nat,
  'product_id' : ProductId,
  'unit_cost' : IDL.Float64,
  'date_received' : Timestamp,
});
export const InventoryLevel = IDL.Record({
  'product_id' : ProductId,
  'total_qty' : IDL.Nat,
  'batches' : IDL.Vec(InventoryBatchPublic),
});
export const MonthlySalesTrend = IDL.Record({
  'month_label' : IDL.Text,
  'total_revenue' : IDL.Float64,
  'total_volume_points' : IDL.Float64,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'mrp' : IDL.Float64,
  'sku' : IDL.Text,
  'owner' : UserId,
  'name' : IDL.Text,
  'earn_base' : IDL.Float64,
  'volume_points' : IDL.Float64,
  'hsn_code' : IDL.Text,
  'category_id' : CategoryId,
});
export const ProfileInput = IDL.Record({
  'business_name' : IDL.Text,
  'email' : IDL.Text,
  'business_address' : IDL.Text,
  'phone_number' : IDL.Text,
  'fssai_number' : IDL.Text,
});
export const PurchaseOrderItem = IDL.Record({
  'product_id' : ProductId,
  'unit_cost' : IDL.Float64,
  'quantity' : IDL.Nat,
  'po_id' : PurchaseOrderId,
});
export const POStatus = IDL.Variant({
  'Received' : IDL.Null,
  'Pending' : IDL.Null,
});
export const PurchaseOrder = IDL.Record({
  'id' : PurchaseOrderId,
  'status' : POStatus,
  'owner' : UserId,
  'vendor' : IDL.Text,
  'timestamp' : Timestamp,
});
export const SaleItem = IDL.Record({
  'unit_cost_snapshot' : IDL.Float64,
  'product_id' : ProductId,
  'product_name_snapshot' : IDL.Text,
  'volume_points_snapshot' : IDL.Float64,
  'quantity' : IDL.Nat,
  'actual_sale_price' : IDL.Float64,
  'sale_id' : SaleId,
  'mrp_snapshot' : IDL.Float64,
});

export const idlService = IDL.Service({
  'createCategory' : IDL.Func([CategoryInput], [CategoryId], []),
  'createProduct' : IDL.Func([ProductInput], [IDL.Opt(ProductId)], []),
  'createPurchaseOrder' : IDL.Func([PurchaseOrderInput], [PurchaseOrderId], []),
  'createSale' : IDL.Func([IDL.Vec(CartItem)], [IDL.Opt(SaleId)], []),
  'deleteCategory' : IDL.Func([CategoryId], [IDL.Bool], []),
  'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getInventoryBatches' : IDL.Func(
      [ProductId],
      [IDL.Vec(InventoryBatchPublic)],
      ['query'],
    ),
  'getInventoryLevels' : IDL.Func([], [IDL.Vec(InventoryLevel)], ['query']),
  'getMonthlySalesTrend' : IDL.Func(
      [],
      [IDL.Vec(MonthlySalesTrend)],
      ['query'],
    ),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(ProfileInput)], ['query']),
  'getPurchaseOrderItems' : IDL.Func(
      [PurchaseOrderId],
      [IDL.Vec(PurchaseOrderItem)],
      ['query'],
    ),
  'getPurchaseOrders' : IDL.Func([], [IDL.Vec(PurchaseOrder)], ['query']),
  'getSale' : IDL.Func([SaleId], [IDL.Opt(Sale)], ['query']),
  'getSaleItems' : IDL.Func([SaleId], [IDL.Vec(SaleItem)], ['query']),
  'getSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
  'markPurchaseOrderReceived' : IDL.Func([PurchaseOrderId], [IDL.Bool], []),
  'updateCategory' : IDL.Func([CategoryId, CategoryInput], [IDL.Bool], []),
  'updateProduct' : IDL.Func([ProductId, ProductInput], [IDL.Bool], []),
  'updateProfile' : IDL.Func([ProfileInput], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CategoryInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const CategoryId = IDL.Nat;
  const ProductInput = IDL.Record({
    'mrp' : IDL.Float64,
    'sku' : IDL.Text,
    'name' : IDL.Text,
    'earn_base' : IDL.Float64,
    'volume_points' : IDL.Float64,
    'hsn_code' : IDL.Text,
    'category_id' : CategoryId,
  });
  const ProductId = IDL.Nat;
  const PurchaseOrderItemInput = IDL.Record({
    'product_id' : ProductId,
    'unit_cost' : IDL.Float64,
    'quantity' : IDL.Nat,
  });
  const PurchaseOrderInput = IDL.Record({
    'vendor' : IDL.Text,
    'items' : IDL.Vec(PurchaseOrderItemInput),
  });
  const PurchaseOrderId = IDL.Nat;
  const CartItem = IDL.Record({
    'product_id' : ProductId,
    'quantity' : IDL.Nat,
    'actual_sale_price' : IDL.Float64,
  });
  const SaleId = IDL.Nat;
  const UserId = IDL.Principal;
  const Category = IDL.Record({
    'id' : CategoryId,
    'owner' : UserId,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const Sale = IDL.Record({
    'id' : SaleId,
    'owner' : UserId,
    'timestamp' : Timestamp,
    'total_revenue' : IDL.Float64,
    'total_volume_points' : IDL.Float64,
    'total_profit' : IDL.Float64,
  });
  const DashboardStats = IDL.Record({
    'monthly_profit' : IDL.Float64,
    'total_inventory_value' : IDL.Float64,
    'recent_sales' : IDL.Vec(Sale),
    'monthly_volume_points' : IDL.Float64,
  });
  const BatchId = IDL.Nat;
  const InventoryBatchPublic = IDL.Record({
    'id' : BatchId,
    'quantity_remaining' : IDL.Nat,
    'product_id' : ProductId,
    'unit_cost' : IDL.Float64,
    'date_received' : Timestamp,
  });
  const InventoryLevel = IDL.Record({
    'product_id' : ProductId,
    'total_qty' : IDL.Nat,
    'batches' : IDL.Vec(InventoryBatchPublic),
  });
  const MonthlySalesTrend = IDL.Record({
    'month_label' : IDL.Text,
    'total_revenue' : IDL.Float64,
    'total_volume_points' : IDL.Float64,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'mrp' : IDL.Float64,
    'sku' : IDL.Text,
    'owner' : UserId,
    'name' : IDL.Text,
    'earn_base' : IDL.Float64,
    'volume_points' : IDL.Float64,
    'hsn_code' : IDL.Text,
    'category_id' : CategoryId,
  });
  const ProfileInput = IDL.Record({
    'business_name' : IDL.Text,
    'email' : IDL.Text,
    'business_address' : IDL.Text,
    'phone_number' : IDL.Text,
    'fssai_number' : IDL.Text,
  });
  const PurchaseOrderItem = IDL.Record({
    'product_id' : ProductId,
    'unit_cost' : IDL.Float64,
    'quantity' : IDL.Nat,
    'po_id' : PurchaseOrderId,
  });
  const POStatus = IDL.Variant({ 'Received' : IDL.Null, 'Pending' : IDL.Null });
  const PurchaseOrder = IDL.Record({
    'id' : PurchaseOrderId,
    'status' : POStatus,
    'owner' : UserId,
    'vendor' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const SaleItem = IDL.Record({
    'unit_cost_snapshot' : IDL.Float64,
    'product_id' : ProductId,
    'product_name_snapshot' : IDL.Text,
    'volume_points_snapshot' : IDL.Float64,
    'quantity' : IDL.Nat,
    'actual_sale_price' : IDL.Float64,
    'sale_id' : SaleId,
    'mrp_snapshot' : IDL.Float64,
  });
  
  return IDL.Service({
    'createCategory' : IDL.Func([CategoryInput], [CategoryId], []),
    'createProduct' : IDL.Func([ProductInput], [IDL.Opt(ProductId)], []),
    'createPurchaseOrder' : IDL.Func(
        [PurchaseOrderInput],
        [PurchaseOrderId],
        [],
      ),
    'createSale' : IDL.Func([IDL.Vec(CartItem)], [IDL.Opt(SaleId)], []),
    'deleteCategory' : IDL.Func([CategoryId], [IDL.Bool], []),
    'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getInventoryBatches' : IDL.Func(
        [ProductId],
        [IDL.Vec(InventoryBatchPublic)],
        ['query'],
      ),
    'getInventoryLevels' : IDL.Func([], [IDL.Vec(InventoryLevel)], ['query']),
    'getMonthlySalesTrend' : IDL.Func(
        [],
        [IDL.Vec(MonthlySalesTrend)],
        ['query'],
      ),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(ProfileInput)], ['query']),
    'getPurchaseOrderItems' : IDL.Func(
        [PurchaseOrderId],
        [IDL.Vec(PurchaseOrderItem)],
        ['query'],
      ),
    'getPurchaseOrders' : IDL.Func([], [IDL.Vec(PurchaseOrder)], ['query']),
    'getSale' : IDL.Func([SaleId], [IDL.Opt(Sale)], ['query']),
    'getSaleItems' : IDL.Func([SaleId], [IDL.Vec(SaleItem)], ['query']),
    'getSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
    'markPurchaseOrderReceived' : IDL.Func([PurchaseOrderId], [IDL.Bool], []),
    'updateCategory' : IDL.Func([CategoryId, CategoryInput], [IDL.Bool], []),
    'updateProduct' : IDL.Func([ProductId, ProductInput], [IDL.Bool], []),
    'updateProfile' : IDL.Func([ProfileInput], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };