/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BatchId = bigint;
export interface BodyCompositionEntry {
  'id' : string,
  'bmi' : [] | [number],
  'bmr' : [] | [number],
  'weight' : [] | [number],
  'date' : string,
  'created_by' : string,
  'visceral_fat' : [] | [number],
  'customer_id' : string,
  'muscle_mass' : [] | [number],
  'body_age' : [] | [bigint],
  'body_fat' : [] | [number],
  'trunk_fat' : [] | [number],
  'profile_key' : ProfileKey,
  'creation_date' : Timestamp,
}
export interface BodyCompositionInput {
  'bmi' : [] | [number],
  'bmr' : [] | [number],
  'weight' : [] | [number],
  'date' : string,
  'visceral_fat' : [] | [number],
  'muscle_mass' : [] | [number],
  'body_age' : [] | [bigint],
  'body_fat' : [] | [number],
  'trunk_fat' : [] | [number],
}
export interface BodyInchesInput {
  'hips' : [] | [number],
  'chest' : [] | [number],
  'entry_date' : Timestamp,
  'thighs' : [] | [number],
  'calves' : [] | [number],
  'waist' : [] | [number],
  'biceps' : [] | [number],
}
export interface BodyInchesPublic {
  'id' : bigint,
  'hips' : [] | [number],
  'chest' : [] | [number],
  'entry_date' : Timestamp,
  'created_by' : string,
  'customer_id' : bigint,
  'thighs' : [] | [number],
  'calves' : [] | [number],
  'waist' : [] | [number],
  'biceps' : [] | [number],
  'profile_key' : ProfileKey,
  'creation_date' : Timestamp,
}
export interface CartItem {
  'is_loaned_item' : [] | [boolean],
  'product_id' : ProductId,
  'product_instructions' : [] | [string],
  'quantity' : bigint,
  'actual_sale_price' : number,
}
export interface Category {
  'id' : CategoryId,
  'owner' : UserId,
  'last_update_date' : Timestamp,
  'name' : string,
  'description' : string,
  'created_by' : UserId,
  'last_updated_by' : UserId,
  'profile_key' : ProfileKey,
  'creation_date' : Timestamp,
}
export type CategoryId = bigint;
export interface CategoryInput { 'name' : string, 'description' : string }
export type CustomerId = bigint;
export interface CustomerInput {
  'age' : [] | [bigint],
  'height' : [] | [string],
  'pin_code' : [] | [string],
  'medical_issue_ids' : [] | [Array<bigint>],
  'body_composition' : [] | [Array<BodyCompositionInput>],
  'country' : [] | [string],
  'address_line1' : [] | [string],
  'address_line2' : [] | [string],
  'referral_commission_amount' : [] | [number],
  'city' : [] | [string],
  'name' : string,
  'note' : [] | [string],
  'referred_by' : [] | [string],
  'discount_value' : [] | [number],
  'lead_follow_up_date' : [] | [bigint],
  'email' : string,
  'discount_applicable' : [] | [DiscountType],
  'state' : [] | [string],
  'lead_to_active_datetime' : [] | [Timestamp],
  'address' : string,
  'gender' : [] | [string],
  'notes' : [] | [Array<CustomerNoteInput>],
  'date_of_birth' : [] | [string],
  'phone' : string,
  'primary_goal_ids' : [] | [Array<bigint>],
  'customer_type' : [] | [
    { 'active' : null } |
      { 'lead' : null } |
      { 'inactive' : null }
  ],
  'lead_notes' : [] | [string],
  'customer_created_by' : [] | [UserId],
}
export interface CustomerNote {
  'id' : bigint,
  'text' : string,
  'created_by' : string,
  'note_date' : Timestamp,
  'creation_date' : Timestamp,
}
export interface CustomerNoteInput { 'text' : string, 'note_date' : Timestamp }
export interface CustomerOrderDetail {
  'sale' : Sale,
  'items' : Array<SaleItem>,
}
export interface CustomerPublic {
  'id' : CustomerId,
  'age' : [] | [bigint],
  'height' : [] | [string],
  'pin_code' : [] | [string],
  'total_sales' : bigint,
  'medical_issue_ids' : Array<bigint>,
  'country' : [] | [string],
  'address_line1' : [] | [string],
  'address_line2' : [] | [string],
  'referral_commission_amount' : [] | [number],
  'city' : [] | [string],
  'name' : string,
  'lifetime_revenue' : number,
  'referred_by' : [] | [string],
  'discount_value' : [] | [number],
  'last_purchase_at' : Timestamp,
  'created_at' : Timestamp,
  'lead_follow_up_date' : [] | [bigint],
  'email' : string,
  'discount_applicable' : [] | [DiscountType],
  'state' : [] | [string],
  'lead_to_active_datetime' : [] | [Timestamp],
  'address' : string,
  'gender' : [] | [string],
  'notes' : Array<CustomerNote>,
  'date_of_birth' : [] | [string],
  'phone' : string,
  'primary_goal_ids' : Array<bigint>,
  'customer_type' : { 'active' : null } |
    { 'lead' : null } |
    { 'inactive' : null },
  'lead_notes' : [] | [string],
  'profile_key' : ProfileKey,
  'customer_created_by' : [] | [UserId],
}
export interface CyclesInfo {
  'profiles_cycles' : Array<ProfileCyclesEntry>,
  'total_cycles' : bigint,
}
export interface DashboardStats {
  'monthly_profit' : number,
  'out_of_stock_count' : bigint,
  'inactive_count' : bigint,
  'total_inventory_value' : number,
  'active_count' : bigint,
  'lead_count' : bigint,
  'recent_sales' : Array<Sale>,
  'monthly_volume_points' : number,
}
export type DiscountType = { 'Fixed' : null } |
  { 'Percentage' : null };
export interface DuplicateCheckResult {
  'similar_customers' : Array<CustomerPublic>,
  'has_similar' : boolean,
}
export interface GoalMasterInput {
  'name' : string,
  'description' : string,
  'product_bundle' : Array<ProductId>,
}
export interface GoalMasterPublic {
  'id' : bigint,
  'last_update_date' : Timestamp,
  'name' : string,
  'description' : string,
  'product_bundle' : Array<ProductId>,
  'creation_date' : Timestamp,
}
export interface GoalMasterPublic__1 {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'product_bundle' : Array<ProductId>,
}
export interface InventoryBatchPublic {
  'id' : BatchId,
  'quantity_remaining' : bigint,
  'product_id' : ProductId,
  'staged_status' : [] | [StagedBatchStatus],
  'unit_cost' : number,
  'loaned_status' : [] | [LoanedItemStatus],
  'loaned_source' : [] | [string],
  'date_received' : Timestamp,
  'warehouse_name' : WarehouseName,
  'return_order_id' : [] | [SaleId],
  'profile_key' : ProfileKey,
  'is_loaned' : boolean,
}
export interface InventoryLevel {
  'product_id' : ProductId,
  'total_qty' : bigint,
  'batches' : Array<InventoryBatchPublic>,
}
export interface InventoryMovement {
  'id' : MovementId,
  'from_warehouse' : WarehouseName,
  'product_id' : ProductId,
  'is_loaned_move' : boolean,
  'last_update_date' : Timestamp,
  'created_by' : UserId,
  'last_updated_by' : UserId,
  'quantity' : bigint,
  'to_warehouse' : WarehouseName,
  'profile_key' : ProfileKey,
  'creation_date' : Timestamp,
  'moved_at' : Timestamp,
  'moved_by' : UserId,
}
export interface InventoryMovementInput {
  'from_warehouse' : WarehouseName,
  'product_id' : ProductId,
  'is_loaned_move' : [] | [boolean],
  'loaned_source' : [] | [string],
  'quantity' : bigint,
  'to_warehouse' : WarehouseName,
}
export interface Lead {
  'id' : bigint,
  'name' : string,
  'business_name' : string,
  'created_at' : Timestamp,
  'email' : string,
  'message' : string,
  'is_closed' : boolean,
  'phone' : string,
  'profile_link' : [] | [string],
}
export interface LeadInput {
  'name' : string,
  'business_name' : string,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export type LoanedItemStatus = { 'active' : null } |
  { 'archived' : null };
export interface LocationMasterEntry {
  'id' : string,
  'name' : string,
  'entry_type' : string,
  'parent_id' : [] | [string],
}
export interface MedicalIssueMasterInput {
  'name' : string,
  'description' : string,
}
export interface MedicalIssueMasterPublic {
  'id' : bigint,
  'last_update_date' : Timestamp,
  'name' : string,
  'description' : string,
  'creation_date' : Timestamp,
}
export interface MedicalIssueMasterPublic__1 {
  'id' : bigint,
  'name' : string,
  'description' : string,
}
export interface MonthlySalesTrend {
  'month_label' : string,
  'total_revenue' : number,
  'total_volume_points' : number,
}
export type MovementId = bigint;
export interface Notification {
  'id' : string,
  'is_read' : boolean,
  'created_at' : Timestamp,
  'notification_type' : string,
  'related_id' : [] | [string],
  'message' : string,
  'profile_key' : string,
  'target_role' : string,
}
export type OrderType = { 'return' : null } |
  { 'standard' : null };
export type POStatus = { 'Received' : null } |
  { 'Pending' : null };
export interface PaymentEntry {
  'id' : string,
  'payment_date' : Timestamp,
  'payment_method' : string,
  'recorded_by' : string,
  'amount' : number,
}
export type PaymentMode = { 'Card' : null } |
  { 'Cash' : null } |
  { 'BankTransfer' : null } |
  { 'Other' : null } |
  { 'Check' : null };
export type PaymentStatus = { 'Paid' : null } |
  { 'Unpaid' : null } |
  { 'Partial' : null };
export interface Product {
  'id' : ProductId,
  'mrp' : number,
  'sku' : string,
  'owner' : UserId,
  'last_update_date' : Timestamp,
  'name' : string,
  'earn_base' : number,
  'created_by' : UserId,
  'instructions' : [] | [string],
  'last_updated_by' : UserId,
  'volume_points' : number,
  'serving_size' : [] | [string],
  'hsn_code' : string,
  'profile_key' : ProfileKey,
  'category_id' : CategoryId,
  'creation_date' : Timestamp,
}
export type ProductId = bigint;
export interface ProductInput {
  'mrp' : number,
  'sku' : string,
  'name' : string,
  'earn_base' : number,
  'instructions' : [] | [string],
  'volume_points' : number,
  'serving_size' : [] | [string],
  'hsn_code' : string,
  'category_id' : CategoryId,
}
export type ProfileApprovalStatus = { 'approved' : null } |
  { 'suspended' : null } |
  { 'pending_super_admin_approval' : null };
export interface ProfileCyclesEntry {
  'business_name' : string,
  'estimated_cycles' : bigint,
  'profile_key' : ProfileKey,
}
export interface ProfileInput {
  'business_name' : string,
  'email' : string,
  'business_address' : string,
  'logo_url' : string,
  'instagram_handle' : string,
  'receipt_notes' : string,
  'phone_number' : string,
  'theme_color' : string,
  'profile_key' : ProfileKey,
  'fssai_number' : string,
}
export type ProfileKey = string;
export interface ProfilePublic {
  'owner' : UserId,
  'is_enabled' : boolean,
  'business_name' : string,
  'end_date' : [] | [Timestamp],
  'created_at' : Timestamp,
  'email' : string,
  'is_archived' : boolean,
  'business_address' : string,
  'start_date' : [] | [Timestamp],
  'logo_url' : string,
  'instagram_handle' : string,
  'profile_approval_status' : ProfileApprovalStatus,
  'receipt_notes' : string,
  'phone_number' : string,
  'theme_color' : string,
  'profile_key' : ProfileKey,
  'fssai_number' : string,
}
export interface ProfileStats {
  'user_count' : bigint,
  'storage_estimate_bytes' : bigint,
  'is_enabled' : boolean,
  'business_name' : string,
  'end_date' : [] | [Timestamp],
  'is_archived' : boolean,
  'start_date' : [] | [Timestamp],
  'last_activity' : Timestamp,
  'owner_principal' : UserId,
  'profile_key' : ProfileKey,
}
export interface ProfileStatus {
  'is_enabled' : boolean,
  'end_date' : [] | [Timestamp],
  'start_date' : [] | [Timestamp],
  'is_within_window' : boolean,
  'profile_approval_status' : ProfileApprovalStatus,
}
export interface PurchaseOrder {
  'id' : PurchaseOrderId,
  'status' : POStatus,
  'po_number' : [] | [string],
  'owner' : UserId,
  'last_update_date' : Timestamp,
  'created_by' : UserId,
  'vendor' : string,
  'last_updated_by' : UserId,
  'timestamp' : Timestamp,
  'warehouse_name' : WarehouseName,
  'vendor_name' : [] | [string],
  'vendor_id' : [] | [string],
  'profile_key' : ProfileKey,
  'creation_date' : Timestamp,
}
export type PurchaseOrderId = bigint;
export interface PurchaseOrderInput {
  'po_number' : [] | [string],
  'vendor' : string,
  'items' : Array<PurchaseOrderItemInput>,
  'warehouse_name' : WarehouseName,
  'vendor_name' : [] | [string],
  'vendor_id' : [] | [string],
}
export interface PurchaseOrderItem {
  'product_id' : ProductId,
  'last_update_date' : Timestamp,
  'unit_cost' : number,
  'created_by' : UserId,
  'last_updated_by' : UserId,
  'quantity' : bigint,
  'po_id' : PurchaseOrderId,
  'creation_date' : Timestamp,
}
export interface PurchaseOrderItemInput {
  'product_id' : ProductId,
  'unit_cost' : number,
  'quantity' : bigint,
}
export interface ReferralCommissionEntry {
  'month' : string,
  'total_commission' : number,
  'customer_count' : bigint,
  'referral_user_principal' : UserId,
  'referral_user_display_name' : string,
  'profile_key' : ProfileKey,
}
export interface ReturnItem {
  'qty' : bigint,
  'product_id' : ProductId,
  'unit_price' : number,
  'is_usable' : boolean,
}
export interface ReturnOrderResult {
  'error' : [] | [string],
  'success' : boolean,
  'return_order_id' : [] | [SaleId],
}
export type RoutingStatus = { 'active' : null } |
  { 'pending_approval' : null } |
  { 'noprofile' : null } |
  { 'superAdmin' : null } |
  { 'profile_pending_super_admin' : null };
export interface Sale {
  'id' : SaleId,
  'return_of_sale_id' : [] | [SaleId],
  'payment_mode' : [] | [PaymentMode],
  'owner' : UserId,
  'last_update_date' : Timestamp,
  'discount_type' : [] | [DiscountType],
  'sale_note' : [] | [string],
  'created_by' : UserId,
  'payment_status' : [] | [PaymentStatus],
  'customer_id' : CustomerId,
  'discount_applied' : [] | [number],
  'sold_by' : UserId,
  'amount_paid' : [] | [number],
  'payment_history' : Array<PaymentEntry>,
  'last_updated_by' : UserId,
  'order_type' : [] | [OrderType],
  'timestamp' : Timestamp,
  'total_revenue' : number,
  'balance_due' : [] | [number],
  'payment_due_date' : [] | [string],
  'customer_name' : string,
  'total_volume_points' : number,
  'profile_key' : ProfileKey,
  'original_subtotal' : [] | [number],
  'creation_date' : Timestamp,
  'total_profit' : number,
}
export type SaleId = bigint;
export interface SaleInput {
  'return_of_sale_id' : [] | [SaleId],
  'payment_mode' : [] | [PaymentMode],
  'sale_note' : [] | [string],
  'cart_items' : Array<CartItem>,
  'payment_status' : [] | [PaymentStatus],
  'customer_id' : CustomerId,
  'amount_paid' : [] | [number],
  'order_type' : [] | [OrderType],
  'payment_due_date' : [] | [string],
}
export interface SaleItem {
  'unit_cost_snapshot' : number,
  'is_loaned_item' : boolean,
  'product_id' : ProductId,
  'last_update_date' : Timestamp,
  'product_instructions' : [] | [string],
  'product_name_snapshot' : string,
  'created_by' : UserId,
  'volume_points_snapshot' : number,
  'last_updated_by' : UserId,
  'quantity' : bigint,
  'actual_sale_price' : number,
  'sale_id' : SaleId,
  'mrp_snapshot' : number,
  'creation_date' : Timestamp,
}
export type StagedBatchStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export interface SuperAdminStats {
  'total_users' : bigint,
  'total_profiles' : bigint,
  'profiles' : Array<ProfileStats>,
}
export type Timestamp = bigint;
export interface UpdateSaleInput {
  'payment_mode' : [] | [PaymentMode],
  'sale_note' : [] | [string],
  'payment_status' : [] | [PaymentStatus],
  'amount_paid' : [] | [number],
  'payment_due_date' : [] | [string],
  'items' : Array<CartItem>,
  'sale_id' : SaleId,
}
export type UserId = Principal;
export interface UserPreferences {
  'theme' : string,
  'defaultReceiptLanguage' : string,
  'language' : string,
  'whatsappNumber' : string,
  'dateFormat' : string,
}
export interface UserProfileInput {
  'theme' : [] | [string],
  'default_receipt_language' : [] | [string],
  'email' : [] | [string],
  'approval_status' : [] | [string],
  'display_name' : string,
  'module_access' : [] | [string],
  'language_preference' : [] | [string],
  'date_format' : [] | [string],
  'warehouse_name' : WarehouseName,
  'profile_key' : ProfileKey,
}
export interface UserProfilePublic {
  'theme' : string,
  'principal' : UserId,
  'default_receipt_language' : string,
  'role' : UserRole,
  'email' : [] | [string],
  'approval_status' : [] | [string],
  'display_name' : string,
  'module_access' : [] | [string],
  'joined_at' : Timestamp,
  'language_preference' : string,
  'date_format' : string,
  'warehouse_name' : WarehouseName,
  'profile_key' : ProfileKey,
}
export type UserRole = { 'admin' : null } |
  { 'referralUser' : null } |
  { 'regularUser' : null } |
  { 'superAdmin' : null } |
  { 'staff' : null };
export interface Vendor {
  'id' : string,
  'last_update_date' : Timestamp,
  'name' : string,
  'created_by' : UserId,
  'email' : [] | [string],
  'is_default' : boolean,
  'address' : [] | [string],
  'last_updated_by' : UserId,
  'contact_name' : [] | [string],
  'phone' : [] | [string],
  'profile_key' : string,
  'creation_date' : Timestamp,
}
export interface VendorInput {
  'name' : string,
  'email' : [] | [string],
  'is_default' : boolean,
  'address' : [] | [string],
  'contact_name' : [] | [string],
  'phone' : [] | [string],
}
export type WarehouseName = string;
export interface _SERVICE {
  'addCustomerNote' : ActorMethod<
    [CustomerId, CustomerNoteInput],
    [] | [CustomerNote]
  >,
  'addLoanerBatch' : ActorMethod<
    [ProductId, bigint, number, string],
    [] | [BatchId]
  >,
  'addLocationEntry' : ActorMethod<[LocationMasterEntry], boolean>,
  'addPaymentEntry' : ActorMethod<[SaleId, number, string], boolean>,
  'approveProfile' : ActorMethod<[ProfileKey], boolean>,
  'approveUser' : ActorMethod<[UserId, boolean], boolean>,
  'archiveLoanedBatch' : ActorMethod<[BatchId], boolean>,
  'assignUserRole' : ActorMethod<[UserId, UserRole, ProfileKey], boolean>,
  'checkAndCreateNotifications' : ActorMethod<[string], bigint>,
  'checkCustomerDuplicate' : ActorMethod<[string], DuplicateCheckResult>,
  /**
   * / Re-claim or confirm Super Admin role. Behaves identically to initSuperAdmin
   * / but is named separately so the frontend can call it to refresh the user record
   * / after a preference change or after recovering from a data clear.
   */
  'claimSuperAdmin' : ActorMethod<[], boolean>,
  /**
   * / Wipes ALL stored data — clears every Map store and resets the super admin principal.
   * / USE IN DEVELOPMENT/PREVIEW ONLY. This is destructive and irreversible.
   * / After clearing, location master data is re-seeded automatically.
   */
  'clearAllData' : ActorMethod<[], undefined>,
  'closeLead' : ActorMethod<[bigint, [] | [string]], boolean>,
  'createBodyCompositionEntry' : ActorMethod<
    [CustomerId, BodyCompositionInput],
    [] | [BodyCompositionEntry]
  >,
  'createBodyInchesEntry' : ActorMethod<
    [CustomerId, BodyInchesInput],
    BodyInchesPublic
  >,
  'createCategory' : ActorMethod<[CategoryInput], CategoryId>,
  'createCustomer' : ActorMethod<[CustomerInput], CustomerId>,
  'createCustomerFromSales' : ActorMethod<[CustomerInput], CustomerId>,
  'createGoal' : ActorMethod<[GoalMasterInput], bigint>,
  'createGoalMaster' : ActorMethod<
    [ProfileKey, string, string],
    GoalMasterPublic__1
  >,
  'createMedicalIssue' : ActorMethod<[MedicalIssueMasterInput], bigint>,
  'createMedicalIssueMaster' : ActorMethod<
    [ProfileKey, string, string],
    MedicalIssueMasterPublic__1
  >,
  'createProduct' : ActorMethod<[ProductInput], [] | [ProductId]>,
  'createProfile' : ActorMethod<[ProfileInput], boolean>,
  'createPurchaseOrder' : ActorMethod<
    [PurchaseOrderInput],
    [] | [PurchaseOrderId]
  >,
  'createReferralUser' : ActorMethod<[ProfileKey, string], boolean>,
  'createReturnOrder' : ActorMethod<
    [SaleId, Array<ReturnItem>],
    ReturnOrderResult
  >,
  'createSale' : ActorMethod<[SaleInput], [] | [SaleId]>,
  'createVendor' : ActorMethod<[VendorInput, string], [] | [Vendor]>,
  'deleteBodyCompositionEntry' : ActorMethod<[string], boolean>,
  'deleteBodyInchesEntry' : ActorMethod<[bigint], boolean>,
  'deleteCategory' : ActorMethod<[CategoryId], boolean>,
  'deleteCustomer' : ActorMethod<[CustomerId], boolean>,
  'deleteCustomerNote' : ActorMethod<[bigint, CustomerId], boolean>,
  'deleteGoal' : ActorMethod<[bigint], boolean>,
  'deleteGoalMaster' : ActorMethod<[bigint], boolean>,
  'deleteLead' : ActorMethod<[bigint], boolean>,
  'deleteMedicalIssue' : ActorMethod<[bigint], boolean>,
  'deleteMedicalIssueMaster' : ActorMethod<[bigint], boolean>,
  'deleteProduct' : ActorMethod<[ProductId], boolean>,
  'deleteProfile' : ActorMethod<[ProfileKey], boolean>,
  'deleteVendor' : ActorMethod<[string], boolean>,
  /**
   * / Public unauthenticated query — returns true if a Super Admin has been set up.
   * / The frontend uses this to decide whether to show the first-time setup screen
   * / (superAdminPrincipal is null) or the normal onboarding screen (it is set).
   */
  'doesSuperAdminExist' : ActorMethod<[], boolean>,
  'enableProfile' : ActorMethod<[ProfileKey, boolean], boolean>,
  'getAllProfilesForAdmin' : ActorMethod<[], Array<ProfilePublic>>,
  'getAllUsersForAdmin' : ActorMethod<[], Array<UserProfilePublic>>,
  'getBodyCompositionHistory' : ActorMethod<
    [CustomerId],
    Array<BodyCompositionEntry>
  >,
  'getCanisterCyclesInfo' : ActorMethod<
    [],
    {
      'per_profile_info' : Array<
        {
          'business_name' : string,
          'cycles_note' : string,
          'profile_key' : string,
        }
      >,
      'total_cycles' : bigint,
    }
  >,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getCitiesByState' : ActorMethod<[string], Array<LocationMasterEntry>>,
  'getCountries' : ActorMethod<[], Array<LocationMasterEntry>>,
  'getCustomer' : ActorMethod<[CustomerId], [] | [CustomerPublic]>,
  'getCustomerOrders' : ActorMethod<[CustomerId], Array<CustomerOrderDetail>>,
  'getCustomers' : ActorMethod<[], Array<CustomerPublic>>,
  'getCyclesInfo' : ActorMethod<[], CyclesInfo>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getGoal' : ActorMethod<[bigint], [] | [GoalMasterPublic]>,
  'getGoalMasterData' : ActorMethod<[ProfileKey], Array<GoalMasterPublic__1>>,
  'getInventoryBatches' : ActorMethod<[ProductId], Array<InventoryBatchPublic>>,
  'getInventoryLevels' : ActorMethod<[], Array<InventoryLevel>>,
  'getInventoryMovements' : ActorMethod<[], Array<InventoryMovement>>,
  'getLastSaleForCustomer' : ActorMethod<
    [CustomerId],
    [] | [CustomerOrderDetail]
  >,
  'getLead' : ActorMethod<[bigint], [] | [Lead]>,
  'getLeads' : ActorMethod<[], Array<Lead>>,
  'getMedicalIssue' : ActorMethod<[bigint], [] | [MedicalIssueMasterPublic]>,
  'getMedicalIssueMasterData' : ActorMethod<
    [ProfileKey],
    Array<MedicalIssueMasterPublic__1>
  >,
  'getMonthlySalesTrend' : ActorMethod<[], Array<MonthlySalesTrend>>,
  'getNotifications' : ActorMethod<[string, string], Array<Notification>>,
  'getNotificationsForUser' : ActorMethod<[], Array<Notification>>,
  'getPaymentHistory' : ActorMethod<[SaleId], Array<PaymentEntry>>,
  'getPendingApprovalUsers' : ActorMethod<
    [ProfileKey],
    Array<UserProfilePublic>
  >,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProfile' : ActorMethod<[], [] | [ProfilePublic]>,
  'getProfileByKey' : ActorMethod<[ProfileKey], [] | [ProfilePublic]>,
  'getProfileStatus' : ActorMethod<[ProfileKey], [] | [ProfileStatus]>,
  'getPurchaseOrderItems' : ActorMethod<
    [PurchaseOrderId],
    Array<PurchaseOrderItem>
  >,
  'getPurchaseOrders' : ActorMethod<[], Array<PurchaseOrder>>,
  'getReferralCommissionByMonth' : ActorMethod<
    [],
    Array<ReferralCommissionEntry>
  >,
  'getReferralUsers' : ActorMethod<[ProfileKey], Array<UserProfilePublic>>,
  'getRoutingStatus' : ActorMethod<[], RoutingStatus>,
  'getSale' : ActorMethod<[SaleId], [] | [Sale]>,
  'getSaleItems' : ActorMethod<[SaleId], Array<SaleItem>>,
  'getSaleWithItems' : ActorMethod<[SaleId], [] | [CustomerOrderDetail]>,
  'getSales' : ActorMethod<[], Array<Sale>>,
  'getSalesByCustomer' : ActorMethod<[CustomerId], Array<Sale>>,
  'getStagedInventory' : ActorMethod<[], Array<InventoryBatchPublic>>,
  'getStates' : ActorMethod<[], Array<LocationMasterEntry>>,
  'getSuperAdminActiveProfile' : ActorMethod<[], [] | [ProfileKey]>,
  'getSuperAdminStats' : ActorMethod<[], SuperAdminStats>,
  'getUserPreferences' : ActorMethod<[], UserPreferences>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getUsersByProfile' : ActorMethod<[ProfileKey], Array<UserProfilePublic>>,
  'getVendor' : ActorMethod<[string], [] | [Vendor]>,
  'getVendors' : ActorMethod<[string], Array<Vendor>>,
  /**
   * / One-time bootstrap: the FIRST caller of this function becomes Super Admin.
   * / If Super Admin is already set, only the same principal can re-confirm (re-run
   * / after clearAllData). Returns true on success, false if already taken by someone else.
   */
  'initSuperAdmin' : ActorMethod<[], boolean>,
  'joinProfile' : ActorMethod<[ProfileKey, string, WarehouseName], boolean>,
  'listBodyInchesHistory' : ActorMethod<[CustomerId], Array<BodyInchesPublic>>,
  'listCustomerNotes' : ActorMethod<[CustomerId], Array<CustomerNote>>,
  'listGoals' : ActorMethod<[], Array<GoalMasterPublic>>,
  'listMedicalIssues' : ActorMethod<[], Array<MedicalIssueMasterPublic>>,
  'markNotificationRead' : ActorMethod<[string], boolean>,
  'markPurchaseOrderReceived' : ActorMethod<[PurchaseOrderId], boolean>,
  'moveInventory' : ActorMethod<[InventoryMovementInput], [] | [MovementId]>,
  'moveLoanerToStaff' : ActorMethod<
    [ProductId, bigint, WarehouseName],
    [] | [MovementId]
  >,
  'rejectProfile' : ActorMethod<[ProfileKey], boolean>,
  'returnToSource' : ActorMethod<[BatchId, bigint], [] | [MovementId]>,
  'reviewStagedItem' : ActorMethod<
    [BatchId, { 'reject' : null } | { 'accept' : null }],
    boolean
  >,
  'runBackgroundChecks' : ActorMethod<[], bigint>,
  'setProfileWindow' : ActorMethod<
    [ProfileKey, [] | [Timestamp], [] | [Timestamp]],
    boolean
  >,
  'setSuperAdminActiveProfile' : ActorMethod<[ProfileKey], boolean>,
  'submitLead' : ActorMethod<[LeadInput], Lead>,
  'updateCategory' : ActorMethod<[CategoryId, CategoryInput], boolean>,
  'updateCustomer' : ActorMethod<[CustomerId, CustomerInput], boolean>,
  'updateGoal' : ActorMethod<[bigint, GoalMasterInput], boolean>,
  'updateGoalMaster' : ActorMethod<
    [bigint, string, string, Array<ProductId>],
    boolean
  >,
  'updateMedicalIssue' : ActorMethod<
    [bigint, MedicalIssueMasterInput],
    boolean
  >,
  'updateMedicalIssueMaster' : ActorMethod<[bigint, string, string], boolean>,
  'updatePaymentStatus' : ActorMethod<
    [SaleId, PaymentStatus, [] | [number], [] | [string]],
    boolean
  >,
  'updateProduct' : ActorMethod<[ProductId, ProductInput], boolean>,
  'updateProfile' : ActorMethod<[ProfileInput], boolean>,
  'updateProfileKey' : ActorMethod<[ProfileKey, ProfileKey], boolean>,
  'updateSale' : ActorMethod<[UpdateSaleInput], boolean>,
  'updateUserPreferences' : ActorMethod<
    [string, string, string, string, string],
    boolean
  >,
  'updateUserProfile' : ActorMethod<[UserProfileInput], boolean>,
  'updateVendor' : ActorMethod<[string, VendorInput], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];