/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CustomerId = IDL.Nat;
export const Timestamp = IDL.Int;
export const CustomerNoteInput = IDL.Record({
  'text' : IDL.Text,
  'note_date' : Timestamp,
});
export const CustomerNote = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'created_by' : IDL.Text,
  'note_date' : Timestamp,
  'creation_date' : Timestamp,
});
export const ProductId = IDL.Nat;
export const BatchId = IDL.Nat;
export const LocationMasterEntry = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'entry_type' : IDL.Text,
  'parent_id' : IDL.Opt(IDL.Text),
});
export const SaleId = IDL.Nat;
export const ProfileKey = IDL.Text;
export const UserId = IDL.Principal;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'referralUser' : IDL.Null,
  'regularUser' : IDL.Null,
  'superAdmin' : IDL.Null,
  'staff' : IDL.Null,
});
export const DiscountType = IDL.Variant({
  'Fixed' : IDL.Null,
  'Percentage' : IDL.Null,
});
export const CustomerPublic = IDL.Record({
  'id' : CustomerId,
  'age' : IDL.Opt(IDL.Nat),
  'height' : IDL.Opt(IDL.Text),
  'pin_code' : IDL.Opt(IDL.Text),
  'total_sales' : IDL.Nat,
  'medical_issue_ids' : IDL.Vec(IDL.Nat),
  'country' : IDL.Opt(IDL.Text),
  'address_line1' : IDL.Opt(IDL.Text),
  'address_line2' : IDL.Opt(IDL.Text),
  'referral_commission_amount' : IDL.Opt(IDL.Float64),
  'city' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'lifetime_revenue' : IDL.Float64,
  'referred_by' : IDL.Opt(IDL.Text),
  'discount_value' : IDL.Opt(IDL.Float64),
  'last_purchase_at' : Timestamp,
  'created_at' : Timestamp,
  'lead_follow_up_date' : IDL.Opt(IDL.Int),
  'email' : IDL.Text,
  'discount_applicable' : IDL.Opt(DiscountType),
  'state' : IDL.Opt(IDL.Text),
  'lead_to_active_datetime' : IDL.Opt(Timestamp),
  'address' : IDL.Text,
  'gender' : IDL.Opt(IDL.Text),
  'notes' : IDL.Vec(CustomerNote),
  'date_of_birth' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
  'primary_goal_ids' : IDL.Vec(IDL.Nat),
  'customer_type' : IDL.Variant({
    'active' : IDL.Null,
    'lead' : IDL.Null,
    'inactive' : IDL.Null,
  }),
  'lead_notes' : IDL.Opt(IDL.Text),
  'profile_key' : ProfileKey,
  'customer_created_by' : IDL.Opt(UserId),
});
export const DuplicateCheckResult = IDL.Record({
  'similar_customers' : IDL.Vec(CustomerPublic),
  'has_similar' : IDL.Bool,
});
export const BodyCompositionInput = IDL.Record({
  'bmi' : IDL.Opt(IDL.Float64),
  'bmr' : IDL.Opt(IDL.Float64),
  'weight' : IDL.Opt(IDL.Float64),
  'date' : IDL.Text,
  'visceral_fat' : IDL.Opt(IDL.Float64),
  'muscle_mass' : IDL.Opt(IDL.Float64),
  'body_age' : IDL.Opt(IDL.Nat),
  'body_fat' : IDL.Opt(IDL.Float64),
  'trunk_fat' : IDL.Opt(IDL.Float64),
});
export const BodyCompositionEntry = IDL.Record({
  'id' : IDL.Text,
  'bmi' : IDL.Opt(IDL.Float64),
  'bmr' : IDL.Opt(IDL.Float64),
  'weight' : IDL.Opt(IDL.Float64),
  'date' : IDL.Text,
  'created_by' : IDL.Text,
  'visceral_fat' : IDL.Opt(IDL.Float64),
  'customer_id' : IDL.Text,
  'muscle_mass' : IDL.Opt(IDL.Float64),
  'body_age' : IDL.Opt(IDL.Nat),
  'body_fat' : IDL.Opt(IDL.Float64),
  'trunk_fat' : IDL.Opt(IDL.Float64),
  'profile_key' : ProfileKey,
  'creation_date' : Timestamp,
});
export const BodyInchesInput = IDL.Record({
  'hips' : IDL.Opt(IDL.Float64),
  'chest' : IDL.Opt(IDL.Float64),
  'entry_date' : Timestamp,
  'thighs' : IDL.Opt(IDL.Float64),
  'calves' : IDL.Opt(IDL.Float64),
  'waist' : IDL.Opt(IDL.Float64),
  'biceps' : IDL.Opt(IDL.Float64),
});
export const BodyInchesPublic = IDL.Record({
  'id' : IDL.Nat,
  'hips' : IDL.Opt(IDL.Float64),
  'chest' : IDL.Opt(IDL.Float64),
  'entry_date' : Timestamp,
  'created_by' : IDL.Text,
  'customer_id' : IDL.Nat,
  'thighs' : IDL.Opt(IDL.Float64),
  'calves' : IDL.Opt(IDL.Float64),
  'waist' : IDL.Opt(IDL.Float64),
  'biceps' : IDL.Opt(IDL.Float64),
  'profile_key' : ProfileKey,
  'creation_date' : Timestamp,
});
export const CategoryInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const CategoryId = IDL.Nat;
export const CustomerInput = IDL.Record({
  'age' : IDL.Opt(IDL.Nat),
  'height' : IDL.Opt(IDL.Text),
  'pin_code' : IDL.Opt(IDL.Text),
  'medical_issue_ids' : IDL.Opt(IDL.Vec(IDL.Nat)),
  'body_composition' : IDL.Opt(IDL.Vec(BodyCompositionInput)),
  'country' : IDL.Opt(IDL.Text),
  'address_line1' : IDL.Opt(IDL.Text),
  'address_line2' : IDL.Opt(IDL.Text),
  'referral_commission_amount' : IDL.Opt(IDL.Float64),
  'city' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
  'referred_by' : IDL.Opt(IDL.Text),
  'discount_value' : IDL.Opt(IDL.Float64),
  'lead_follow_up_date' : IDL.Opt(IDL.Int),
  'email' : IDL.Text,
  'discount_applicable' : IDL.Opt(DiscountType),
  'state' : IDL.Opt(IDL.Text),
  'lead_to_active_datetime' : IDL.Opt(Timestamp),
  'address' : IDL.Text,
  'gender' : IDL.Opt(IDL.Text),
  'notes' : IDL.Opt(IDL.Vec(CustomerNoteInput)),
  'date_of_birth' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
  'primary_goal_ids' : IDL.Opt(IDL.Vec(IDL.Nat)),
  'customer_type' : IDL.Opt(
    IDL.Variant({
      'active' : IDL.Null,
      'lead' : IDL.Null,
      'inactive' : IDL.Null,
    })
  ),
  'lead_notes' : IDL.Opt(IDL.Text),
  'customer_created_by' : IDL.Opt(UserId),
});
export const GoalMasterInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'product_bundle' : IDL.Vec(ProductId),
});
export const GoalMasterPublic__1 = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'product_bundle' : IDL.Vec(ProductId),
});
export const MedicalIssueMasterInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const MedicalIssueMasterPublic__1 = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const ProductInput = IDL.Record({
  'mrp' : IDL.Float64,
  'sku' : IDL.Text,
  'name' : IDL.Text,
  'earn_base' : IDL.Float64,
  'instructions' : IDL.Opt(IDL.Text),
  'volume_points' : IDL.Float64,
  'serving_size' : IDL.Opt(IDL.Text),
  'hsn_code' : IDL.Text,
  'category_id' : CategoryId,
});
export const ProfileInput = IDL.Record({
  'business_name' : IDL.Text,
  'email' : IDL.Text,
  'business_address' : IDL.Text,
  'logo_url' : IDL.Text,
  'instagram_handle' : IDL.Text,
  'receipt_notes' : IDL.Text,
  'phone_number' : IDL.Text,
  'theme_color' : IDL.Text,
  'profile_key' : ProfileKey,
  'fssai_number' : IDL.Text,
});
export const PurchaseOrderItemInput = IDL.Record({
  'product_id' : ProductId,
  'unit_cost' : IDL.Float64,
  'quantity' : IDL.Nat,
});
export const WarehouseName = IDL.Text;
export const PurchaseOrderInput = IDL.Record({
  'po_number' : IDL.Opt(IDL.Text),
  'vendor' : IDL.Text,
  'items' : IDL.Vec(PurchaseOrderItemInput),
  'warehouse_name' : WarehouseName,
  'vendor_name' : IDL.Opt(IDL.Text),
  'vendor_id' : IDL.Opt(IDL.Text),
});
export const PurchaseOrderId = IDL.Nat;
export const ReturnItem = IDL.Record({
  'qty' : IDL.Nat,
  'product_id' : ProductId,
  'unit_price' : IDL.Float64,
  'is_usable' : IDL.Bool,
});
export const ReturnOrderResult = IDL.Record({
  'error' : IDL.Opt(IDL.Text),
  'success' : IDL.Bool,
  'return_order_id' : IDL.Opt(SaleId),
});
export const PaymentMode = IDL.Variant({
  'Card' : IDL.Null,
  'Cash' : IDL.Null,
  'BankTransfer' : IDL.Null,
  'Other' : IDL.Null,
  'Check' : IDL.Null,
});
export const CartItem = IDL.Record({
  'is_loaned_item' : IDL.Opt(IDL.Bool),
  'product_id' : ProductId,
  'product_instructions' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Nat,
  'actual_sale_price' : IDL.Float64,
});
export const PaymentStatus = IDL.Variant({
  'Paid' : IDL.Null,
  'Unpaid' : IDL.Null,
  'Partial' : IDL.Null,
});
export const OrderType = IDL.Variant({
  'return' : IDL.Null,
  'standard' : IDL.Null,
});
export const SaleInput = IDL.Record({
  'return_of_sale_id' : IDL.Opt(SaleId),
  'payment_mode' : IDL.Opt(PaymentMode),
  'sale_note' : IDL.Opt(IDL.Text),
  'cart_items' : IDL.Vec(CartItem),
  'payment_status' : IDL.Opt(PaymentStatus),
  'customer_id' : CustomerId,
  'amount_paid' : IDL.Opt(IDL.Float64),
  'order_type' : IDL.Opt(OrderType),
  'payment_due_date' : IDL.Opt(IDL.Text),
});
export const VendorInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'is_default' : IDL.Bool,
  'address' : IDL.Opt(IDL.Text),
  'contact_name' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const Vendor = IDL.Record({
  'id' : IDL.Text,
  'last_update_date' : Timestamp,
  'name' : IDL.Text,
  'created_by' : UserId,
  'email' : IDL.Opt(IDL.Text),
  'is_default' : IDL.Bool,
  'address' : IDL.Opt(IDL.Text),
  'last_updated_by' : UserId,
  'contact_name' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
  'profile_key' : IDL.Text,
  'creation_date' : Timestamp,
});
export const ProfileApprovalStatus = IDL.Variant({
  'approved' : IDL.Null,
  'suspended' : IDL.Null,
  'pending_super_admin_approval' : IDL.Null,
});
export const ProfilePublic = IDL.Record({
  'owner' : UserId,
  'is_enabled' : IDL.Bool,
  'business_name' : IDL.Text,
  'end_date' : IDL.Opt(Timestamp),
  'created_at' : Timestamp,
  'email' : IDL.Text,
  'is_archived' : IDL.Bool,
  'business_address' : IDL.Text,
  'start_date' : IDL.Opt(Timestamp),
  'logo_url' : IDL.Text,
  'instagram_handle' : IDL.Text,
  'profile_approval_status' : ProfileApprovalStatus,
  'receipt_notes' : IDL.Text,
  'phone_number' : IDL.Text,
  'theme_color' : IDL.Text,
  'profile_key' : ProfileKey,
  'fssai_number' : IDL.Text,
});
export const UserProfilePublic = IDL.Record({
  'principal' : UserId,
  'default_receipt_language' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Opt(IDL.Text),
  'approval_status' : IDL.Opt(IDL.Text),
  'display_name' : IDL.Text,
  'module_access' : IDL.Opt(IDL.Text),
  'joined_at' : Timestamp,
  'language_preference' : IDL.Text,
  'date_format' : IDL.Text,
  'warehouse_name' : WarehouseName,
  'profile_key' : ProfileKey,
});
export const Category = IDL.Record({
  'id' : CategoryId,
  'owner' : UserId,
  'last_update_date' : Timestamp,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'created_by' : UserId,
  'last_updated_by' : UserId,
  'profile_key' : ProfileKey,
  'creation_date' : Timestamp,
});
export const PaymentEntry = IDL.Record({
  'id' : IDL.Text,
  'payment_date' : Timestamp,
  'payment_method' : IDL.Text,
  'recorded_by' : IDL.Text,
  'amount' : IDL.Float64,
});
export const Sale = IDL.Record({
  'id' : SaleId,
  'return_of_sale_id' : IDL.Opt(SaleId),
  'payment_mode' : IDL.Opt(PaymentMode),
  'owner' : UserId,
  'last_update_date' : Timestamp,
  'discount_type' : IDL.Opt(DiscountType),
  'sale_note' : IDL.Opt(IDL.Text),
  'created_by' : UserId,
  'payment_status' : IDL.Opt(PaymentStatus),
  'customer_id' : CustomerId,
  'discount_applied' : IDL.Opt(IDL.Float64),
  'sold_by' : UserId,
  'amount_paid' : IDL.Opt(IDL.Float64),
  'payment_history' : IDL.Vec(PaymentEntry),
  'last_updated_by' : UserId,
  'order_type' : IDL.Opt(OrderType),
  'timestamp' : Timestamp,
  'total_revenue' : IDL.Float64,
  'balance_due' : IDL.Opt(IDL.Float64),
  'payment_due_date' : IDL.Opt(IDL.Text),
  'customer_name' : IDL.Text,
  'total_volume_points' : IDL.Float64,
  'profile_key' : ProfileKey,
  'original_subtotal' : IDL.Opt(IDL.Float64),
  'creation_date' : Timestamp,
  'total_profit' : IDL.Float64,
});
export const SaleItem = IDL.Record({
  'unit_cost_snapshot' : IDL.Float64,
  'is_loaned_item' : IDL.Bool,
  'product_id' : ProductId,
  'last_update_date' : Timestamp,
  'product_instructions' : IDL.Opt(IDL.Text),
  'product_name_snapshot' : IDL.Text,
  'created_by' : UserId,
  'volume_points_snapshot' : IDL.Float64,
  'last_updated_by' : UserId,
  'quantity' : IDL.Nat,
  'actual_sale_price' : IDL.Float64,
  'sale_id' : SaleId,
  'mrp_snapshot' : IDL.Float64,
  'creation_date' : Timestamp,
});
export const CustomerOrderDetail = IDL.Record({
  'sale' : Sale,
  'items' : IDL.Vec(SaleItem),
});
export const ProfileCyclesEntry = IDL.Record({
  'business_name' : IDL.Text,
  'estimated_cycles' : IDL.Nat,
  'profile_key' : ProfileKey,
});
export const CyclesInfo = IDL.Record({
  'profiles_cycles' : IDL.Vec(ProfileCyclesEntry),
  'total_cycles' : IDL.Nat,
});
export const DashboardStats = IDL.Record({
  'monthly_profit' : IDL.Float64,
  'inactive_count' : IDL.Nat,
  'total_inventory_value' : IDL.Float64,
  'active_count' : IDL.Nat,
  'lead_count' : IDL.Nat,
  'recent_sales' : IDL.Vec(Sale),
  'monthly_volume_points' : IDL.Float64,
});
export const GoalMasterPublic = IDL.Record({
  'id' : IDL.Nat,
  'last_update_date' : Timestamp,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'product_bundle' : IDL.Vec(ProductId),
  'creation_date' : Timestamp,
});
export const StagedBatchStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const LoanedItemStatus = IDL.Variant({
  'active' : IDL.Null,
  'archived' : IDL.Null,
});
export const InventoryBatchPublic = IDL.Record({
  'id' : BatchId,
  'quantity_remaining' : IDL.Nat,
  'product_id' : ProductId,
  'staged_status' : IDL.Opt(StagedBatchStatus),
  'unit_cost' : IDL.Float64,
  'loaned_status' : IDL.Opt(LoanedItemStatus),
  'loaned_source' : IDL.Opt(IDL.Text),
  'date_received' : Timestamp,
  'warehouse_name' : WarehouseName,
  'return_order_id' : IDL.Opt(SaleId),
  'profile_key' : ProfileKey,
  'is_loaned' : IDL.Bool,
});
export const InventoryLevel = IDL.Record({
  'product_id' : ProductId,
  'total_qty' : IDL.Nat,
  'batches' : IDL.Vec(InventoryBatchPublic),
});
export const MovementId = IDL.Nat;
export const InventoryMovement = IDL.Record({
  'id' : MovementId,
  'from_warehouse' : WarehouseName,
  'product_id' : ProductId,
  'is_loaned_move' : IDL.Bool,
  'last_update_date' : Timestamp,
  'created_by' : UserId,
  'last_updated_by' : UserId,
  'quantity' : IDL.Nat,
  'to_warehouse' : WarehouseName,
  'profile_key' : ProfileKey,
  'creation_date' : Timestamp,
  'moved_at' : Timestamp,
  'moved_by' : UserId,
});
export const MedicalIssueMasterPublic = IDL.Record({
  'id' : IDL.Nat,
  'last_update_date' : Timestamp,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'creation_date' : Timestamp,
});
export const MonthlySalesTrend = IDL.Record({
  'month_label' : IDL.Text,
  'total_revenue' : IDL.Float64,
  'total_volume_points' : IDL.Float64,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'is_read' : IDL.Bool,
  'created_at' : Timestamp,
  'notification_type' : IDL.Text,
  'related_id' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'profile_key' : IDL.Text,
  'target_role' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'mrp' : IDL.Float64,
  'sku' : IDL.Text,
  'owner' : UserId,
  'last_update_date' : Timestamp,
  'name' : IDL.Text,
  'earn_base' : IDL.Float64,
  'created_by' : UserId,
  'instructions' : IDL.Opt(IDL.Text),
  'last_updated_by' : UserId,
  'volume_points' : IDL.Float64,
  'serving_size' : IDL.Opt(IDL.Text),
  'hsn_code' : IDL.Text,
  'profile_key' : ProfileKey,
  'category_id' : CategoryId,
  'creation_date' : Timestamp,
});
export const ProfileStatus = IDL.Record({
  'is_enabled' : IDL.Bool,
  'end_date' : IDL.Opt(Timestamp),
  'start_date' : IDL.Opt(Timestamp),
  'is_within_window' : IDL.Bool,
  'profile_approval_status' : ProfileApprovalStatus,
});
export const PurchaseOrderItem = IDL.Record({
  'product_id' : ProductId,
  'last_update_date' : Timestamp,
  'unit_cost' : IDL.Float64,
  'created_by' : UserId,
  'last_updated_by' : UserId,
  'quantity' : IDL.Nat,
  'po_id' : PurchaseOrderId,
  'creation_date' : Timestamp,
});
export const POStatus = IDL.Variant({
  'Received' : IDL.Null,
  'Pending' : IDL.Null,
});
export const PurchaseOrder = IDL.Record({
  'id' : PurchaseOrderId,
  'status' : POStatus,
  'po_number' : IDL.Opt(IDL.Text),
  'owner' : UserId,
  'last_update_date' : Timestamp,
  'created_by' : UserId,
  'vendor' : IDL.Text,
  'last_updated_by' : UserId,
  'timestamp' : Timestamp,
  'warehouse_name' : WarehouseName,
  'vendor_name' : IDL.Opt(IDL.Text),
  'vendor_id' : IDL.Opt(IDL.Text),
  'profile_key' : ProfileKey,
  'creation_date' : Timestamp,
});
export const ReferralCommissionEntry = IDL.Record({
  'month' : IDL.Text,
  'total_commission' : IDL.Float64,
  'customer_count' : IDL.Nat,
  'referral_user_principal' : UserId,
  'referral_user_display_name' : IDL.Text,
  'profile_key' : ProfileKey,
});
export const RoutingStatus = IDL.Variant({
  'active' : IDL.Null,
  'pending_approval' : IDL.Null,
  'noprofile' : IDL.Null,
  'superAdmin' : IDL.Null,
  'profile_pending_super_admin' : IDL.Null,
});
export const ProfileStats = IDL.Record({
  'user_count' : IDL.Nat,
  'storage_estimate_bytes' : IDL.Nat,
  'is_enabled' : IDL.Bool,
  'business_name' : IDL.Text,
  'end_date' : IDL.Opt(Timestamp),
  'is_archived' : IDL.Bool,
  'start_date' : IDL.Opt(Timestamp),
  'last_activity' : Timestamp,
  'owner_principal' : UserId,
  'profile_key' : ProfileKey,
});
export const SuperAdminStats = IDL.Record({
  'total_users' : IDL.Nat,
  'total_profiles' : IDL.Nat,
  'profiles' : IDL.Vec(ProfileStats),
});
export const UserPreferences = IDL.Record({
  'defaultReceiptLanguage' : IDL.Text,
  'language' : IDL.Text,
  'whatsappNumber' : IDL.Text,
  'dateFormat' : IDL.Text,
});
export const InventoryMovementInput = IDL.Record({
  'from_warehouse' : WarehouseName,
  'product_id' : ProductId,
  'is_loaned_move' : IDL.Opt(IDL.Bool),
  'loaned_source' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Nat,
  'to_warehouse' : WarehouseName,
});
export const UpdateSaleInput = IDL.Record({
  'payment_mode' : IDL.Opt(PaymentMode),
  'sale_note' : IDL.Opt(IDL.Text),
  'payment_status' : IDL.Opt(PaymentStatus),
  'amount_paid' : IDL.Opt(IDL.Float64),
  'payment_due_date' : IDL.Opt(IDL.Text),
  'items' : IDL.Vec(CartItem),
  'sale_id' : SaleId,
});
export const UserProfileInput = IDL.Record({
  'default_receipt_language' : IDL.Opt(IDL.Text),
  'email' : IDL.Opt(IDL.Text),
  'approval_status' : IDL.Opt(IDL.Text),
  'display_name' : IDL.Text,
  'module_access' : IDL.Opt(IDL.Text),
  'language_preference' : IDL.Opt(IDL.Text),
  'date_format' : IDL.Opt(IDL.Text),
  'warehouse_name' : WarehouseName,
  'profile_key' : ProfileKey,
});

export const idlService = IDL.Service({
  'addCustomerNote' : IDL.Func(
      [CustomerId, CustomerNoteInput],
      [IDL.Opt(CustomerNote)],
      [],
    ),
  'addLoanerBatch' : IDL.Func(
      [ProductId, IDL.Nat, IDL.Float64, IDL.Text],
      [IDL.Opt(BatchId)],
      [],
    ),
  'addLocationEntry' : IDL.Func([LocationMasterEntry], [IDL.Bool], []),
  'addPaymentEntry' : IDL.Func([SaleId, IDL.Float64, IDL.Text], [IDL.Bool], []),
  'approveProfile' : IDL.Func([ProfileKey], [IDL.Bool], []),
  'approveUser' : IDL.Func([UserId, IDL.Bool], [IDL.Bool], []),
  'archiveLoanedBatch' : IDL.Func([BatchId], [IDL.Bool], []),
  'assignUserRole' : IDL.Func([UserId, UserRole, ProfileKey], [IDL.Bool], []),
  'checkAndCreateNotifications' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'checkCustomerDuplicate' : IDL.Func(
      [IDL.Text],
      [DuplicateCheckResult],
      ['query'],
    ),
  'claimSuperAdmin' : IDL.Func([], [IDL.Bool], []),
  'clearAllData' : IDL.Func([], [], []),
  'createBodyCompositionEntry' : IDL.Func(
      [CustomerId, BodyCompositionInput],
      [IDL.Opt(BodyCompositionEntry)],
      [],
    ),
  'createBodyInchesEntry' : IDL.Func(
      [CustomerId, BodyInchesInput],
      [BodyInchesPublic],
      [],
    ),
  'createCategory' : IDL.Func([CategoryInput], [CategoryId], []),
  'createCustomer' : IDL.Func([CustomerInput], [CustomerId], []),
  'createCustomerFromSales' : IDL.Func([CustomerInput], [CustomerId], []),
  'createGoal' : IDL.Func([GoalMasterInput], [IDL.Nat], []),
  'createGoalMaster' : IDL.Func(
      [ProfileKey, IDL.Text, IDL.Text],
      [GoalMasterPublic__1],
      [],
    ),
  'createMedicalIssue' : IDL.Func([MedicalIssueMasterInput], [IDL.Nat], []),
  'createMedicalIssueMaster' : IDL.Func(
      [ProfileKey, IDL.Text, IDL.Text],
      [MedicalIssueMasterPublic__1],
      [],
    ),
  'createProduct' : IDL.Func([ProductInput], [IDL.Opt(ProductId)], []),
  'createProfile' : IDL.Func([ProfileInput], [IDL.Bool], []),
  'createPurchaseOrder' : IDL.Func(
      [PurchaseOrderInput],
      [IDL.Opt(PurchaseOrderId)],
      [],
    ),
  'createReferralUser' : IDL.Func([ProfileKey, IDL.Text], [IDL.Bool], []),
  'createReturnOrder' : IDL.Func(
      [SaleId, IDL.Vec(ReturnItem)],
      [ReturnOrderResult],
      [],
    ),
  'createSale' : IDL.Func([SaleInput], [IDL.Opt(SaleId)], []),
  'createVendor' : IDL.Func([VendorInput, IDL.Text], [IDL.Opt(Vendor)], []),
  'deleteBodyCompositionEntry' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteBodyInchesEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteCategory' : IDL.Func([CategoryId], [IDL.Bool], []),
  'deleteCustomer' : IDL.Func([CustomerId], [IDL.Bool], []),
  'deleteCustomerNote' : IDL.Func([IDL.Nat, CustomerId], [IDL.Bool], []),
  'deleteGoal' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteGoalMaster' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteMedicalIssue' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteMedicalIssueMaster' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'deleteProfile' : IDL.Func([ProfileKey], [IDL.Bool], []),
  'deleteVendor' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'doesSuperAdminExist' : IDL.Func([], [IDL.Bool], ['query']),
  'enableProfile' : IDL.Func([ProfileKey, IDL.Bool], [IDL.Bool], []),
  'getAllProfilesForAdmin' : IDL.Func([], [IDL.Vec(ProfilePublic)], ['query']),
  'getAllUsersForAdmin' : IDL.Func([], [IDL.Vec(UserProfilePublic)], ['query']),
  'getBodyCompositionHistory' : IDL.Func(
      [CustomerId],
      [IDL.Vec(BodyCompositionEntry)],
      ['query'],
    ),
  'getCanisterCyclesInfo' : IDL.Func(
      [],
      [
        IDL.Record({
          'per_profile_info' : IDL.Vec(
            IDL.Record({
              'business_name' : IDL.Text,
              'cycles_note' : IDL.Text,
              'profile_key' : IDL.Text,
            })
          ),
          'total_cycles' : IDL.Nat,
        }),
      ],
      [],
    ),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getCitiesByState' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LocationMasterEntry)],
      ['query'],
    ),
  'getCountries' : IDL.Func([], [IDL.Vec(LocationMasterEntry)], ['query']),
  'getCustomer' : IDL.Func([CustomerId], [IDL.Opt(CustomerPublic)], ['query']),
  'getCustomerOrders' : IDL.Func(
      [CustomerId],
      [IDL.Vec(CustomerOrderDetail)],
      ['query'],
    ),
  'getCustomers' : IDL.Func([], [IDL.Vec(CustomerPublic)], ['query']),
  'getCyclesInfo' : IDL.Func([], [CyclesInfo], []),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getGoal' : IDL.Func([IDL.Nat], [IDL.Opt(GoalMasterPublic)], ['query']),
  'getGoalMasterData' : IDL.Func(
      [ProfileKey],
      [IDL.Vec(GoalMasterPublic__1)],
      ['query'],
    ),
  'getInventoryBatches' : IDL.Func(
      [ProductId],
      [IDL.Vec(InventoryBatchPublic)],
      ['query'],
    ),
  'getInventoryLevels' : IDL.Func([], [IDL.Vec(InventoryLevel)], ['query']),
  'getInventoryMovements' : IDL.Func(
      [],
      [IDL.Vec(InventoryMovement)],
      ['query'],
    ),
  'getLastSaleForCustomer' : IDL.Func(
      [CustomerId],
      [IDL.Opt(CustomerOrderDetail)],
      ['query'],
    ),
  'getMedicalIssue' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(MedicalIssueMasterPublic)],
      ['query'],
    ),
  'getMedicalIssueMasterData' : IDL.Func(
      [ProfileKey],
      [IDL.Vec(MedicalIssueMasterPublic__1)],
      ['query'],
    ),
  'getMonthlySalesTrend' : IDL.Func(
      [],
      [IDL.Vec(MonthlySalesTrend)],
      ['query'],
    ),
  'getNotifications' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'getNotificationsForUser' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPaymentHistory' : IDL.Func([SaleId], [IDL.Vec(PaymentEntry)], ['query']),
  'getPendingApprovalUsers' : IDL.Func(
      [ProfileKey],
      [IDL.Vec(UserProfilePublic)],
      ['query'],
    ),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(ProfilePublic)], ['query']),
  'getProfileByKey' : IDL.Func(
      [ProfileKey],
      [IDL.Opt(ProfilePublic)],
      ['query'],
    ),
  'getProfileStatus' : IDL.Func(
      [ProfileKey],
      [IDL.Opt(ProfileStatus)],
      ['query'],
    ),
  'getPurchaseOrderItems' : IDL.Func(
      [PurchaseOrderId],
      [IDL.Vec(PurchaseOrderItem)],
      ['query'],
    ),
  'getPurchaseOrders' : IDL.Func([], [IDL.Vec(PurchaseOrder)], ['query']),
  'getReferralCommissionByMonth' : IDL.Func(
      [],
      [IDL.Vec(ReferralCommissionEntry)],
      ['query'],
    ),
  'getReferralUsers' : IDL.Func(
      [ProfileKey],
      [IDL.Vec(UserProfilePublic)],
      ['query'],
    ),
  'getRoutingStatus' : IDL.Func([], [RoutingStatus], []),
  'getSale' : IDL.Func([SaleId], [IDL.Opt(Sale)], ['query']),
  'getSaleItems' : IDL.Func([SaleId], [IDL.Vec(SaleItem)], ['query']),
  'getSaleWithItems' : IDL.Func(
      [SaleId],
      [IDL.Opt(CustomerOrderDetail)],
      ['query'],
    ),
  'getSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
  'getSalesByCustomer' : IDL.Func([CustomerId], [IDL.Vec(Sale)], ['query']),
  'getStagedInventory' : IDL.Func(
      [],
      [IDL.Vec(InventoryBatchPublic)],
      ['query'],
    ),
  'getStates' : IDL.Func([], [IDL.Vec(LocationMasterEntry)], ['query']),
  'getSuperAdminActiveProfile' : IDL.Func([], [IDL.Opt(ProfileKey)], ['query']),
  'getSuperAdminStats' : IDL.Func([], [SuperAdminStats], ['query']),
  'getUserPreferences' : IDL.Func([], [UserPreferences], ['query']),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
  'getUsersByProfile' : IDL.Func(
      [ProfileKey],
      [IDL.Vec(UserProfilePublic)],
      ['query'],
    ),
  'getVendor' : IDL.Func([IDL.Text], [IDL.Opt(Vendor)], ['query']),
  'getVendors' : IDL.Func([IDL.Text], [IDL.Vec(Vendor)], ['query']),
  'initSuperAdmin' : IDL.Func([], [IDL.Bool], []),
  'joinProfile' : IDL.Func(
      [ProfileKey, IDL.Text, WarehouseName],
      [IDL.Bool],
      [],
    ),
  'listBodyInchesHistory' : IDL.Func(
      [CustomerId],
      [IDL.Vec(BodyInchesPublic)],
      ['query'],
    ),
  'listCustomerNotes' : IDL.Func(
      [CustomerId],
      [IDL.Vec(CustomerNote)],
      ['query'],
    ),
  'listGoals' : IDL.Func([], [IDL.Vec(GoalMasterPublic)], ['query']),
  'listMedicalIssues' : IDL.Func(
      [],
      [IDL.Vec(MedicalIssueMasterPublic)],
      ['query'],
    ),
  'markNotificationRead' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'markPurchaseOrderReceived' : IDL.Func([PurchaseOrderId], [IDL.Bool], []),
  'moveInventory' : IDL.Func(
      [InventoryMovementInput],
      [IDL.Opt(MovementId)],
      [],
    ),
  'moveLoanerToStaff' : IDL.Func(
      [ProductId, IDL.Nat, WarehouseName],
      [IDL.Opt(MovementId)],
      [],
    ),
  'rejectProfile' : IDL.Func([ProfileKey], [IDL.Bool], []),
  'returnToSource' : IDL.Func([BatchId, IDL.Nat], [IDL.Opt(MovementId)], []),
  'reviewStagedItem' : IDL.Func(
      [BatchId, IDL.Variant({ 'reject' : IDL.Null, 'accept' : IDL.Null })],
      [IDL.Bool],
      [],
    ),
  'runBackgroundChecks' : IDL.Func([], [IDL.Nat], []),
  'setProfileWindow' : IDL.Func(
      [ProfileKey, IDL.Opt(Timestamp), IDL.Opt(Timestamp)],
      [IDL.Bool],
      [],
    ),
  'setSuperAdminActiveProfile' : IDL.Func([ProfileKey], [IDL.Bool], []),
  'updateCategory' : IDL.Func([CategoryId, CategoryInput], [IDL.Bool], []),
  'updateCustomer' : IDL.Func([CustomerId, CustomerInput], [IDL.Bool], []),
  'updateGoal' : IDL.Func([IDL.Nat, GoalMasterInput], [IDL.Bool], []),
  'updateGoalMaster' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(ProductId)],
      [IDL.Bool],
      [],
    ),
  'updateMedicalIssue' : IDL.Func(
      [IDL.Nat, MedicalIssueMasterInput],
      [IDL.Bool],
      [],
    ),
  'updateMedicalIssueMaster' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updatePaymentStatus' : IDL.Func(
      [SaleId, PaymentStatus, IDL.Opt(IDL.Float64), IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'updateProduct' : IDL.Func([ProductId, ProductInput], [IDL.Bool], []),
  'updateProfile' : IDL.Func([ProfileInput], [IDL.Bool], []),
  'updateProfileKey' : IDL.Func([ProfileKey, ProfileKey], [IDL.Bool], []),
  'updateSale' : IDL.Func([UpdateSaleInput], [IDL.Bool], []),
  'updateUserPreferences' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateUserProfile' : IDL.Func([UserProfileInput], [IDL.Bool], []),
  'updateVendor' : IDL.Func([IDL.Text, VendorInput], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CustomerId = IDL.Nat;
  const Timestamp = IDL.Int;
  const CustomerNoteInput = IDL.Record({
    'text' : IDL.Text,
    'note_date' : Timestamp,
  });
  const CustomerNote = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'created_by' : IDL.Text,
    'note_date' : Timestamp,
    'creation_date' : Timestamp,
  });
  const ProductId = IDL.Nat;
  const BatchId = IDL.Nat;
  const LocationMasterEntry = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'entry_type' : IDL.Text,
    'parent_id' : IDL.Opt(IDL.Text),
  });
  const SaleId = IDL.Nat;
  const ProfileKey = IDL.Text;
  const UserId = IDL.Principal;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'referralUser' : IDL.Null,
    'regularUser' : IDL.Null,
    'superAdmin' : IDL.Null,
    'staff' : IDL.Null,
  });
  const DiscountType = IDL.Variant({
    'Fixed' : IDL.Null,
    'Percentage' : IDL.Null,
  });
  const CustomerPublic = IDL.Record({
    'id' : CustomerId,
    'age' : IDL.Opt(IDL.Nat),
    'height' : IDL.Opt(IDL.Text),
    'pin_code' : IDL.Opt(IDL.Text),
    'total_sales' : IDL.Nat,
    'medical_issue_ids' : IDL.Vec(IDL.Nat),
    'country' : IDL.Opt(IDL.Text),
    'address_line1' : IDL.Opt(IDL.Text),
    'address_line2' : IDL.Opt(IDL.Text),
    'referral_commission_amount' : IDL.Opt(IDL.Float64),
    'city' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'lifetime_revenue' : IDL.Float64,
    'referred_by' : IDL.Opt(IDL.Text),
    'discount_value' : IDL.Opt(IDL.Float64),
    'last_purchase_at' : Timestamp,
    'created_at' : Timestamp,
    'lead_follow_up_date' : IDL.Opt(IDL.Int),
    'email' : IDL.Text,
    'discount_applicable' : IDL.Opt(DiscountType),
    'state' : IDL.Opt(IDL.Text),
    'lead_to_active_datetime' : IDL.Opt(Timestamp),
    'address' : IDL.Text,
    'gender' : IDL.Opt(IDL.Text),
    'notes' : IDL.Vec(CustomerNote),
    'date_of_birth' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
    'primary_goal_ids' : IDL.Vec(IDL.Nat),
    'customer_type' : IDL.Variant({
      'active' : IDL.Null,
      'lead' : IDL.Null,
      'inactive' : IDL.Null,
    }),
    'lead_notes' : IDL.Opt(IDL.Text),
    'profile_key' : ProfileKey,
    'customer_created_by' : IDL.Opt(UserId),
  });
  const DuplicateCheckResult = IDL.Record({
    'similar_customers' : IDL.Vec(CustomerPublic),
    'has_similar' : IDL.Bool,
  });
  const BodyCompositionInput = IDL.Record({
    'bmi' : IDL.Opt(IDL.Float64),
    'bmr' : IDL.Opt(IDL.Float64),
    'weight' : IDL.Opt(IDL.Float64),
    'date' : IDL.Text,
    'visceral_fat' : IDL.Opt(IDL.Float64),
    'muscle_mass' : IDL.Opt(IDL.Float64),
    'body_age' : IDL.Opt(IDL.Nat),
    'body_fat' : IDL.Opt(IDL.Float64),
    'trunk_fat' : IDL.Opt(IDL.Float64),
  });
  const BodyCompositionEntry = IDL.Record({
    'id' : IDL.Text,
    'bmi' : IDL.Opt(IDL.Float64),
    'bmr' : IDL.Opt(IDL.Float64),
    'weight' : IDL.Opt(IDL.Float64),
    'date' : IDL.Text,
    'created_by' : IDL.Text,
    'visceral_fat' : IDL.Opt(IDL.Float64),
    'customer_id' : IDL.Text,
    'muscle_mass' : IDL.Opt(IDL.Float64),
    'body_age' : IDL.Opt(IDL.Nat),
    'body_fat' : IDL.Opt(IDL.Float64),
    'trunk_fat' : IDL.Opt(IDL.Float64),
    'profile_key' : ProfileKey,
    'creation_date' : Timestamp,
  });
  const BodyInchesInput = IDL.Record({
    'hips' : IDL.Opt(IDL.Float64),
    'chest' : IDL.Opt(IDL.Float64),
    'entry_date' : Timestamp,
    'thighs' : IDL.Opt(IDL.Float64),
    'calves' : IDL.Opt(IDL.Float64),
    'waist' : IDL.Opt(IDL.Float64),
    'biceps' : IDL.Opt(IDL.Float64),
  });
  const BodyInchesPublic = IDL.Record({
    'id' : IDL.Nat,
    'hips' : IDL.Opt(IDL.Float64),
    'chest' : IDL.Opt(IDL.Float64),
    'entry_date' : Timestamp,
    'created_by' : IDL.Text,
    'customer_id' : IDL.Nat,
    'thighs' : IDL.Opt(IDL.Float64),
    'calves' : IDL.Opt(IDL.Float64),
    'waist' : IDL.Opt(IDL.Float64),
    'biceps' : IDL.Opt(IDL.Float64),
    'profile_key' : ProfileKey,
    'creation_date' : Timestamp,
  });
  const CategoryInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const CategoryId = IDL.Nat;
  const CustomerInput = IDL.Record({
    'age' : IDL.Opt(IDL.Nat),
    'height' : IDL.Opt(IDL.Text),
    'pin_code' : IDL.Opt(IDL.Text),
    'medical_issue_ids' : IDL.Opt(IDL.Vec(IDL.Nat)),
    'body_composition' : IDL.Opt(IDL.Vec(BodyCompositionInput)),
    'country' : IDL.Opt(IDL.Text),
    'address_line1' : IDL.Opt(IDL.Text),
    'address_line2' : IDL.Opt(IDL.Text),
    'referral_commission_amount' : IDL.Opt(IDL.Float64),
    'city' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
    'referred_by' : IDL.Opt(IDL.Text),
    'discount_value' : IDL.Opt(IDL.Float64),
    'lead_follow_up_date' : IDL.Opt(IDL.Int),
    'email' : IDL.Text,
    'discount_applicable' : IDL.Opt(DiscountType),
    'state' : IDL.Opt(IDL.Text),
    'lead_to_active_datetime' : IDL.Opt(Timestamp),
    'address' : IDL.Text,
    'gender' : IDL.Opt(IDL.Text),
    'notes' : IDL.Opt(IDL.Vec(CustomerNoteInput)),
    'date_of_birth' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
    'primary_goal_ids' : IDL.Opt(IDL.Vec(IDL.Nat)),
    'customer_type' : IDL.Opt(
      IDL.Variant({
        'active' : IDL.Null,
        'lead' : IDL.Null,
        'inactive' : IDL.Null,
      })
    ),
    'lead_notes' : IDL.Opt(IDL.Text),
    'customer_created_by' : IDL.Opt(UserId),
  });
  const GoalMasterInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'product_bundle' : IDL.Vec(ProductId),
  });
  const GoalMasterPublic__1 = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'product_bundle' : IDL.Vec(ProductId),
  });
  const MedicalIssueMasterInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const MedicalIssueMasterPublic__1 = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const ProductInput = IDL.Record({
    'mrp' : IDL.Float64,
    'sku' : IDL.Text,
    'name' : IDL.Text,
    'earn_base' : IDL.Float64,
    'instructions' : IDL.Opt(IDL.Text),
    'volume_points' : IDL.Float64,
    'serving_size' : IDL.Opt(IDL.Text),
    'hsn_code' : IDL.Text,
    'category_id' : CategoryId,
  });
  const ProfileInput = IDL.Record({
    'business_name' : IDL.Text,
    'email' : IDL.Text,
    'business_address' : IDL.Text,
    'logo_url' : IDL.Text,
    'instagram_handle' : IDL.Text,
    'receipt_notes' : IDL.Text,
    'phone_number' : IDL.Text,
    'theme_color' : IDL.Text,
    'profile_key' : ProfileKey,
    'fssai_number' : IDL.Text,
  });
  const PurchaseOrderItemInput = IDL.Record({
    'product_id' : ProductId,
    'unit_cost' : IDL.Float64,
    'quantity' : IDL.Nat,
  });
  const WarehouseName = IDL.Text;
  const PurchaseOrderInput = IDL.Record({
    'po_number' : IDL.Opt(IDL.Text),
    'vendor' : IDL.Text,
    'items' : IDL.Vec(PurchaseOrderItemInput),
    'warehouse_name' : WarehouseName,
    'vendor_name' : IDL.Opt(IDL.Text),
    'vendor_id' : IDL.Opt(IDL.Text),
  });
  const PurchaseOrderId = IDL.Nat;
  const ReturnItem = IDL.Record({
    'qty' : IDL.Nat,
    'product_id' : ProductId,
    'unit_price' : IDL.Float64,
    'is_usable' : IDL.Bool,
  });
  const ReturnOrderResult = IDL.Record({
    'error' : IDL.Opt(IDL.Text),
    'success' : IDL.Bool,
    'return_order_id' : IDL.Opt(SaleId),
  });
  const PaymentMode = IDL.Variant({
    'Card' : IDL.Null,
    'Cash' : IDL.Null,
    'BankTransfer' : IDL.Null,
    'Other' : IDL.Null,
    'Check' : IDL.Null,
  });
  const CartItem = IDL.Record({
    'is_loaned_item' : IDL.Opt(IDL.Bool),
    'product_id' : ProductId,
    'product_instructions' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Nat,
    'actual_sale_price' : IDL.Float64,
  });
  const PaymentStatus = IDL.Variant({
    'Paid' : IDL.Null,
    'Unpaid' : IDL.Null,
    'Partial' : IDL.Null,
  });
  const OrderType = IDL.Variant({ 'return' : IDL.Null, 'standard' : IDL.Null });
  const SaleInput = IDL.Record({
    'return_of_sale_id' : IDL.Opt(SaleId),
    'payment_mode' : IDL.Opt(PaymentMode),
    'sale_note' : IDL.Opt(IDL.Text),
    'cart_items' : IDL.Vec(CartItem),
    'payment_status' : IDL.Opt(PaymentStatus),
    'customer_id' : CustomerId,
    'amount_paid' : IDL.Opt(IDL.Float64),
    'order_type' : IDL.Opt(OrderType),
    'payment_due_date' : IDL.Opt(IDL.Text),
  });
  const VendorInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'is_default' : IDL.Bool,
    'address' : IDL.Opt(IDL.Text),
    'contact_name' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const Vendor = IDL.Record({
    'id' : IDL.Text,
    'last_update_date' : Timestamp,
    'name' : IDL.Text,
    'created_by' : UserId,
    'email' : IDL.Opt(IDL.Text),
    'is_default' : IDL.Bool,
    'address' : IDL.Opt(IDL.Text),
    'last_updated_by' : UserId,
    'contact_name' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
    'profile_key' : IDL.Text,
    'creation_date' : Timestamp,
  });
  const ProfileApprovalStatus = IDL.Variant({
    'approved' : IDL.Null,
    'suspended' : IDL.Null,
    'pending_super_admin_approval' : IDL.Null,
  });
  const ProfilePublic = IDL.Record({
    'owner' : UserId,
    'is_enabled' : IDL.Bool,
    'business_name' : IDL.Text,
    'end_date' : IDL.Opt(Timestamp),
    'created_at' : Timestamp,
    'email' : IDL.Text,
    'is_archived' : IDL.Bool,
    'business_address' : IDL.Text,
    'start_date' : IDL.Opt(Timestamp),
    'logo_url' : IDL.Text,
    'instagram_handle' : IDL.Text,
    'profile_approval_status' : ProfileApprovalStatus,
    'receipt_notes' : IDL.Text,
    'phone_number' : IDL.Text,
    'theme_color' : IDL.Text,
    'profile_key' : ProfileKey,
    'fssai_number' : IDL.Text,
  });
  const UserProfilePublic = IDL.Record({
    'principal' : UserId,
    'default_receipt_language' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Opt(IDL.Text),
    'approval_status' : IDL.Opt(IDL.Text),
    'display_name' : IDL.Text,
    'module_access' : IDL.Opt(IDL.Text),
    'joined_at' : Timestamp,
    'language_preference' : IDL.Text,
    'date_format' : IDL.Text,
    'warehouse_name' : WarehouseName,
    'profile_key' : ProfileKey,
  });
  const Category = IDL.Record({
    'id' : CategoryId,
    'owner' : UserId,
    'last_update_date' : Timestamp,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'created_by' : UserId,
    'last_updated_by' : UserId,
    'profile_key' : ProfileKey,
    'creation_date' : Timestamp,
  });
  const PaymentEntry = IDL.Record({
    'id' : IDL.Text,
    'payment_date' : Timestamp,
    'payment_method' : IDL.Text,
    'recorded_by' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const Sale = IDL.Record({
    'id' : SaleId,
    'return_of_sale_id' : IDL.Opt(SaleId),
    'payment_mode' : IDL.Opt(PaymentMode),
    'owner' : UserId,
    'last_update_date' : Timestamp,
    'discount_type' : IDL.Opt(DiscountType),
    'sale_note' : IDL.Opt(IDL.Text),
    'created_by' : UserId,
    'payment_status' : IDL.Opt(PaymentStatus),
    'customer_id' : CustomerId,
    'discount_applied' : IDL.Opt(IDL.Float64),
    'sold_by' : UserId,
    'amount_paid' : IDL.Opt(IDL.Float64),
    'payment_history' : IDL.Vec(PaymentEntry),
    'last_updated_by' : UserId,
    'order_type' : IDL.Opt(OrderType),
    'timestamp' : Timestamp,
    'total_revenue' : IDL.Float64,
    'balance_due' : IDL.Opt(IDL.Float64),
    'payment_due_date' : IDL.Opt(IDL.Text),
    'customer_name' : IDL.Text,
    'total_volume_points' : IDL.Float64,
    'profile_key' : ProfileKey,
    'original_subtotal' : IDL.Opt(IDL.Float64),
    'creation_date' : Timestamp,
    'total_profit' : IDL.Float64,
  });
  const SaleItem = IDL.Record({
    'unit_cost_snapshot' : IDL.Float64,
    'is_loaned_item' : IDL.Bool,
    'product_id' : ProductId,
    'last_update_date' : Timestamp,
    'product_instructions' : IDL.Opt(IDL.Text),
    'product_name_snapshot' : IDL.Text,
    'created_by' : UserId,
    'volume_points_snapshot' : IDL.Float64,
    'last_updated_by' : UserId,
    'quantity' : IDL.Nat,
    'actual_sale_price' : IDL.Float64,
    'sale_id' : SaleId,
    'mrp_snapshot' : IDL.Float64,
    'creation_date' : Timestamp,
  });
  const CustomerOrderDetail = IDL.Record({
    'sale' : Sale,
    'items' : IDL.Vec(SaleItem),
  });
  const ProfileCyclesEntry = IDL.Record({
    'business_name' : IDL.Text,
    'estimated_cycles' : IDL.Nat,
    'profile_key' : ProfileKey,
  });
  const CyclesInfo = IDL.Record({
    'profiles_cycles' : IDL.Vec(ProfileCyclesEntry),
    'total_cycles' : IDL.Nat,
  });
  const DashboardStats = IDL.Record({
    'monthly_profit' : IDL.Float64,
    'inactive_count' : IDL.Nat,
    'total_inventory_value' : IDL.Float64,
    'active_count' : IDL.Nat,
    'lead_count' : IDL.Nat,
    'recent_sales' : IDL.Vec(Sale),
    'monthly_volume_points' : IDL.Float64,
  });
  const GoalMasterPublic = IDL.Record({
    'id' : IDL.Nat,
    'last_update_date' : Timestamp,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'product_bundle' : IDL.Vec(ProductId),
    'creation_date' : Timestamp,
  });
  const StagedBatchStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const LoanedItemStatus = IDL.Variant({
    'active' : IDL.Null,
    'archived' : IDL.Null,
  });
  const InventoryBatchPublic = IDL.Record({
    'id' : BatchId,
    'quantity_remaining' : IDL.Nat,
    'product_id' : ProductId,
    'staged_status' : IDL.Opt(StagedBatchStatus),
    'unit_cost' : IDL.Float64,
    'loaned_status' : IDL.Opt(LoanedItemStatus),
    'loaned_source' : IDL.Opt(IDL.Text),
    'date_received' : Timestamp,
    'warehouse_name' : WarehouseName,
    'return_order_id' : IDL.Opt(SaleId),
    'profile_key' : ProfileKey,
    'is_loaned' : IDL.Bool,
  });
  const InventoryLevel = IDL.Record({
    'product_id' : ProductId,
    'total_qty' : IDL.Nat,
    'batches' : IDL.Vec(InventoryBatchPublic),
  });
  const MovementId = IDL.Nat;
  const InventoryMovement = IDL.Record({
    'id' : MovementId,
    'from_warehouse' : WarehouseName,
    'product_id' : ProductId,
    'is_loaned_move' : IDL.Bool,
    'last_update_date' : Timestamp,
    'created_by' : UserId,
    'last_updated_by' : UserId,
    'quantity' : IDL.Nat,
    'to_warehouse' : WarehouseName,
    'profile_key' : ProfileKey,
    'creation_date' : Timestamp,
    'moved_at' : Timestamp,
    'moved_by' : UserId,
  });
  const MedicalIssueMasterPublic = IDL.Record({
    'id' : IDL.Nat,
    'last_update_date' : Timestamp,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'creation_date' : Timestamp,
  });
  const MonthlySalesTrend = IDL.Record({
    'month_label' : IDL.Text,
    'total_revenue' : IDL.Float64,
    'total_volume_points' : IDL.Float64,
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'is_read' : IDL.Bool,
    'created_at' : Timestamp,
    'notification_type' : IDL.Text,
    'related_id' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'profile_key' : IDL.Text,
    'target_role' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'mrp' : IDL.Float64,
    'sku' : IDL.Text,
    'owner' : UserId,
    'last_update_date' : Timestamp,
    'name' : IDL.Text,
    'earn_base' : IDL.Float64,
    'created_by' : UserId,
    'instructions' : IDL.Opt(IDL.Text),
    'last_updated_by' : UserId,
    'volume_points' : IDL.Float64,
    'serving_size' : IDL.Opt(IDL.Text),
    'hsn_code' : IDL.Text,
    'profile_key' : ProfileKey,
    'category_id' : CategoryId,
    'creation_date' : Timestamp,
  });
  const ProfileStatus = IDL.Record({
    'is_enabled' : IDL.Bool,
    'end_date' : IDL.Opt(Timestamp),
    'start_date' : IDL.Opt(Timestamp),
    'is_within_window' : IDL.Bool,
    'profile_approval_status' : ProfileApprovalStatus,
  });
  const PurchaseOrderItem = IDL.Record({
    'product_id' : ProductId,
    'last_update_date' : Timestamp,
    'unit_cost' : IDL.Float64,
    'created_by' : UserId,
    'last_updated_by' : UserId,
    'quantity' : IDL.Nat,
    'po_id' : PurchaseOrderId,
    'creation_date' : Timestamp,
  });
  const POStatus = IDL.Variant({ 'Received' : IDL.Null, 'Pending' : IDL.Null });
  const PurchaseOrder = IDL.Record({
    'id' : PurchaseOrderId,
    'status' : POStatus,
    'po_number' : IDL.Opt(IDL.Text),
    'owner' : UserId,
    'last_update_date' : Timestamp,
    'created_by' : UserId,
    'vendor' : IDL.Text,
    'last_updated_by' : UserId,
    'timestamp' : Timestamp,
    'warehouse_name' : WarehouseName,
    'vendor_name' : IDL.Opt(IDL.Text),
    'vendor_id' : IDL.Opt(IDL.Text),
    'profile_key' : ProfileKey,
    'creation_date' : Timestamp,
  });
  const ReferralCommissionEntry = IDL.Record({
    'month' : IDL.Text,
    'total_commission' : IDL.Float64,
    'customer_count' : IDL.Nat,
    'referral_user_principal' : UserId,
    'referral_user_display_name' : IDL.Text,
    'profile_key' : ProfileKey,
  });
  const RoutingStatus = IDL.Variant({
    'active' : IDL.Null,
    'pending_approval' : IDL.Null,
    'noprofile' : IDL.Null,
    'superAdmin' : IDL.Null,
    'profile_pending_super_admin' : IDL.Null,
  });
  const ProfileStats = IDL.Record({
    'user_count' : IDL.Nat,
    'storage_estimate_bytes' : IDL.Nat,
    'is_enabled' : IDL.Bool,
    'business_name' : IDL.Text,
    'end_date' : IDL.Opt(Timestamp),
    'is_archived' : IDL.Bool,
    'start_date' : IDL.Opt(Timestamp),
    'last_activity' : Timestamp,
    'owner_principal' : UserId,
    'profile_key' : ProfileKey,
  });
  const SuperAdminStats = IDL.Record({
    'total_users' : IDL.Nat,
    'total_profiles' : IDL.Nat,
    'profiles' : IDL.Vec(ProfileStats),
  });
  const UserPreferences = IDL.Record({
    'defaultReceiptLanguage' : IDL.Text,
    'language' : IDL.Text,
    'whatsappNumber' : IDL.Text,
    'dateFormat' : IDL.Text,
  });
  const InventoryMovementInput = IDL.Record({
    'from_warehouse' : WarehouseName,
    'product_id' : ProductId,
    'is_loaned_move' : IDL.Opt(IDL.Bool),
    'loaned_source' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Nat,
    'to_warehouse' : WarehouseName,
  });
  const UpdateSaleInput = IDL.Record({
    'payment_mode' : IDL.Opt(PaymentMode),
    'sale_note' : IDL.Opt(IDL.Text),
    'payment_status' : IDL.Opt(PaymentStatus),
    'amount_paid' : IDL.Opt(IDL.Float64),
    'payment_due_date' : IDL.Opt(IDL.Text),
    'items' : IDL.Vec(CartItem),
    'sale_id' : SaleId,
  });
  const UserProfileInput = IDL.Record({
    'default_receipt_language' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
    'approval_status' : IDL.Opt(IDL.Text),
    'display_name' : IDL.Text,
    'module_access' : IDL.Opt(IDL.Text),
    'language_preference' : IDL.Opt(IDL.Text),
    'date_format' : IDL.Opt(IDL.Text),
    'warehouse_name' : WarehouseName,
    'profile_key' : ProfileKey,
  });
  
  return IDL.Service({
    'addCustomerNote' : IDL.Func(
        [CustomerId, CustomerNoteInput],
        [IDL.Opt(CustomerNote)],
        [],
      ),
    'addLoanerBatch' : IDL.Func(
        [ProductId, IDL.Nat, IDL.Float64, IDL.Text],
        [IDL.Opt(BatchId)],
        [],
      ),
    'addLocationEntry' : IDL.Func([LocationMasterEntry], [IDL.Bool], []),
    'addPaymentEntry' : IDL.Func(
        [SaleId, IDL.Float64, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'approveProfile' : IDL.Func([ProfileKey], [IDL.Bool], []),
    'approveUser' : IDL.Func([UserId, IDL.Bool], [IDL.Bool], []),
    'archiveLoanedBatch' : IDL.Func([BatchId], [IDL.Bool], []),
    'assignUserRole' : IDL.Func([UserId, UserRole, ProfileKey], [IDL.Bool], []),
    'checkAndCreateNotifications' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'checkCustomerDuplicate' : IDL.Func(
        [IDL.Text],
        [DuplicateCheckResult],
        ['query'],
      ),
    'claimSuperAdmin' : IDL.Func([], [IDL.Bool], []),
    'clearAllData' : IDL.Func([], [], []),
    'createBodyCompositionEntry' : IDL.Func(
        [CustomerId, BodyCompositionInput],
        [IDL.Opt(BodyCompositionEntry)],
        [],
      ),
    'createBodyInchesEntry' : IDL.Func(
        [CustomerId, BodyInchesInput],
        [BodyInchesPublic],
        [],
      ),
    'createCategory' : IDL.Func([CategoryInput], [CategoryId], []),
    'createCustomer' : IDL.Func([CustomerInput], [CustomerId], []),
    'createCustomerFromSales' : IDL.Func([CustomerInput], [CustomerId], []),
    'createGoal' : IDL.Func([GoalMasterInput], [IDL.Nat], []),
    'createGoalMaster' : IDL.Func(
        [ProfileKey, IDL.Text, IDL.Text],
        [GoalMasterPublic__1],
        [],
      ),
    'createMedicalIssue' : IDL.Func([MedicalIssueMasterInput], [IDL.Nat], []),
    'createMedicalIssueMaster' : IDL.Func(
        [ProfileKey, IDL.Text, IDL.Text],
        [MedicalIssueMasterPublic__1],
        [],
      ),
    'createProduct' : IDL.Func([ProductInput], [IDL.Opt(ProductId)], []),
    'createProfile' : IDL.Func([ProfileInput], [IDL.Bool], []),
    'createPurchaseOrder' : IDL.Func(
        [PurchaseOrderInput],
        [IDL.Opt(PurchaseOrderId)],
        [],
      ),
    'createReferralUser' : IDL.Func([ProfileKey, IDL.Text], [IDL.Bool], []),
    'createReturnOrder' : IDL.Func(
        [SaleId, IDL.Vec(ReturnItem)],
        [ReturnOrderResult],
        [],
      ),
    'createSale' : IDL.Func([SaleInput], [IDL.Opt(SaleId)], []),
    'createVendor' : IDL.Func([VendorInput, IDL.Text], [IDL.Opt(Vendor)], []),
    'deleteBodyCompositionEntry' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteBodyInchesEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteCategory' : IDL.Func([CategoryId], [IDL.Bool], []),
    'deleteCustomer' : IDL.Func([CustomerId], [IDL.Bool], []),
    'deleteCustomerNote' : IDL.Func([IDL.Nat, CustomerId], [IDL.Bool], []),
    'deleteGoal' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteGoalMaster' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteMedicalIssue' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteMedicalIssueMaster' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'deleteProfile' : IDL.Func([ProfileKey], [IDL.Bool], []),
    'deleteVendor' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'doesSuperAdminExist' : IDL.Func([], [IDL.Bool], ['query']),
    'enableProfile' : IDL.Func([ProfileKey, IDL.Bool], [IDL.Bool], []),
    'getAllProfilesForAdmin' : IDL.Func(
        [],
        [IDL.Vec(ProfilePublic)],
        ['query'],
      ),
    'getAllUsersForAdmin' : IDL.Func(
        [],
        [IDL.Vec(UserProfilePublic)],
        ['query'],
      ),
    'getBodyCompositionHistory' : IDL.Func(
        [CustomerId],
        [IDL.Vec(BodyCompositionEntry)],
        ['query'],
      ),
    'getCanisterCyclesInfo' : IDL.Func(
        [],
        [
          IDL.Record({
            'per_profile_info' : IDL.Vec(
              IDL.Record({
                'business_name' : IDL.Text,
                'cycles_note' : IDL.Text,
                'profile_key' : IDL.Text,
              })
            ),
            'total_cycles' : IDL.Nat,
          }),
        ],
        [],
      ),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getCitiesByState' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LocationMasterEntry)],
        ['query'],
      ),
    'getCountries' : IDL.Func([], [IDL.Vec(LocationMasterEntry)], ['query']),
    'getCustomer' : IDL.Func(
        [CustomerId],
        [IDL.Opt(CustomerPublic)],
        ['query'],
      ),
    'getCustomerOrders' : IDL.Func(
        [CustomerId],
        [IDL.Vec(CustomerOrderDetail)],
        ['query'],
      ),
    'getCustomers' : IDL.Func([], [IDL.Vec(CustomerPublic)], ['query']),
    'getCyclesInfo' : IDL.Func([], [CyclesInfo], []),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getGoal' : IDL.Func([IDL.Nat], [IDL.Opt(GoalMasterPublic)], ['query']),
    'getGoalMasterData' : IDL.Func(
        [ProfileKey],
        [IDL.Vec(GoalMasterPublic__1)],
        ['query'],
      ),
    'getInventoryBatches' : IDL.Func(
        [ProductId],
        [IDL.Vec(InventoryBatchPublic)],
        ['query'],
      ),
    'getInventoryLevels' : IDL.Func([], [IDL.Vec(InventoryLevel)], ['query']),
    'getInventoryMovements' : IDL.Func(
        [],
        [IDL.Vec(InventoryMovement)],
        ['query'],
      ),
    'getLastSaleForCustomer' : IDL.Func(
        [CustomerId],
        [IDL.Opt(CustomerOrderDetail)],
        ['query'],
      ),
    'getMedicalIssue' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(MedicalIssueMasterPublic)],
        ['query'],
      ),
    'getMedicalIssueMasterData' : IDL.Func(
        [ProfileKey],
        [IDL.Vec(MedicalIssueMasterPublic__1)],
        ['query'],
      ),
    'getMonthlySalesTrend' : IDL.Func(
        [],
        [IDL.Vec(MonthlySalesTrend)],
        ['query'],
      ),
    'getNotifications' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getNotificationsForUser' : IDL.Func(
        [],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getPaymentHistory' : IDL.Func(
        [SaleId],
        [IDL.Vec(PaymentEntry)],
        ['query'],
      ),
    'getPendingApprovalUsers' : IDL.Func(
        [ProfileKey],
        [IDL.Vec(UserProfilePublic)],
        ['query'],
      ),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(ProfilePublic)], ['query']),
    'getProfileByKey' : IDL.Func(
        [ProfileKey],
        [IDL.Opt(ProfilePublic)],
        ['query'],
      ),
    'getProfileStatus' : IDL.Func(
        [ProfileKey],
        [IDL.Opt(ProfileStatus)],
        ['query'],
      ),
    'getPurchaseOrderItems' : IDL.Func(
        [PurchaseOrderId],
        [IDL.Vec(PurchaseOrderItem)],
        ['query'],
      ),
    'getPurchaseOrders' : IDL.Func([], [IDL.Vec(PurchaseOrder)], ['query']),
    'getReferralCommissionByMonth' : IDL.Func(
        [],
        [IDL.Vec(ReferralCommissionEntry)],
        ['query'],
      ),
    'getReferralUsers' : IDL.Func(
        [ProfileKey],
        [IDL.Vec(UserProfilePublic)],
        ['query'],
      ),
    'getRoutingStatus' : IDL.Func([], [RoutingStatus], []),
    'getSale' : IDL.Func([SaleId], [IDL.Opt(Sale)], ['query']),
    'getSaleItems' : IDL.Func([SaleId], [IDL.Vec(SaleItem)], ['query']),
    'getSaleWithItems' : IDL.Func(
        [SaleId],
        [IDL.Opt(CustomerOrderDetail)],
        ['query'],
      ),
    'getSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
    'getSalesByCustomer' : IDL.Func([CustomerId], [IDL.Vec(Sale)], ['query']),
    'getStagedInventory' : IDL.Func(
        [],
        [IDL.Vec(InventoryBatchPublic)],
        ['query'],
      ),
    'getStates' : IDL.Func([], [IDL.Vec(LocationMasterEntry)], ['query']),
    'getSuperAdminActiveProfile' : IDL.Func(
        [],
        [IDL.Opt(ProfileKey)],
        ['query'],
      ),
    'getSuperAdminStats' : IDL.Func([], [SuperAdminStats], ['query']),
    'getUserPreferences' : IDL.Func([], [UserPreferences], ['query']),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
    'getUsersByProfile' : IDL.Func(
        [ProfileKey],
        [IDL.Vec(UserProfilePublic)],
        ['query'],
      ),
    'getVendor' : IDL.Func([IDL.Text], [IDL.Opt(Vendor)], ['query']),
    'getVendors' : IDL.Func([IDL.Text], [IDL.Vec(Vendor)], ['query']),
    'initSuperAdmin' : IDL.Func([], [IDL.Bool], []),
    'joinProfile' : IDL.Func(
        [ProfileKey, IDL.Text, WarehouseName],
        [IDL.Bool],
        [],
      ),
    'listBodyInchesHistory' : IDL.Func(
        [CustomerId],
        [IDL.Vec(BodyInchesPublic)],
        ['query'],
      ),
    'listCustomerNotes' : IDL.Func(
        [CustomerId],
        [IDL.Vec(CustomerNote)],
        ['query'],
      ),
    'listGoals' : IDL.Func([], [IDL.Vec(GoalMasterPublic)], ['query']),
    'listMedicalIssues' : IDL.Func(
        [],
        [IDL.Vec(MedicalIssueMasterPublic)],
        ['query'],
      ),
    'markNotificationRead' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'markPurchaseOrderReceived' : IDL.Func([PurchaseOrderId], [IDL.Bool], []),
    'moveInventory' : IDL.Func(
        [InventoryMovementInput],
        [IDL.Opt(MovementId)],
        [],
      ),
    'moveLoanerToStaff' : IDL.Func(
        [ProductId, IDL.Nat, WarehouseName],
        [IDL.Opt(MovementId)],
        [],
      ),
    'rejectProfile' : IDL.Func([ProfileKey], [IDL.Bool], []),
    'returnToSource' : IDL.Func([BatchId, IDL.Nat], [IDL.Opt(MovementId)], []),
    'reviewStagedItem' : IDL.Func(
        [BatchId, IDL.Variant({ 'reject' : IDL.Null, 'accept' : IDL.Null })],
        [IDL.Bool],
        [],
      ),
    'runBackgroundChecks' : IDL.Func([], [IDL.Nat], []),
    'setProfileWindow' : IDL.Func(
        [ProfileKey, IDL.Opt(Timestamp), IDL.Opt(Timestamp)],
        [IDL.Bool],
        [],
      ),
    'setSuperAdminActiveProfile' : IDL.Func([ProfileKey], [IDL.Bool], []),
    'updateCategory' : IDL.Func([CategoryId, CategoryInput], [IDL.Bool], []),
    'updateCustomer' : IDL.Func([CustomerId, CustomerInput], [IDL.Bool], []),
    'updateGoal' : IDL.Func([IDL.Nat, GoalMasterInput], [IDL.Bool], []),
    'updateGoalMaster' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(ProductId)],
        [IDL.Bool],
        [],
      ),
    'updateMedicalIssue' : IDL.Func(
        [IDL.Nat, MedicalIssueMasterInput],
        [IDL.Bool],
        [],
      ),
    'updateMedicalIssueMaster' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updatePaymentStatus' : IDL.Func(
        [SaleId, PaymentStatus, IDL.Opt(IDL.Float64), IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'updateProduct' : IDL.Func([ProductId, ProductInput], [IDL.Bool], []),
    'updateProfile' : IDL.Func([ProfileInput], [IDL.Bool], []),
    'updateProfileKey' : IDL.Func([ProfileKey, ProfileKey], [IDL.Bool], []),
    'updateSale' : IDL.Func([UpdateSaleInput], [IDL.Bool], []),
    'updateUserPreferences' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateUserProfile' : IDL.Func([UserProfileInput], [IDL.Bool], []),
    'updateVendor' : IDL.Func([IDL.Text, VendorInput], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };