/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ProductInput {
    mrp: number;
    sku: string;
    name: string;
    earn_base: number;
    volume_points: number;
    hsn_code: string;
    category_id: CategoryId;
}
export type Timestamp = bigint;
export interface InventoryLevel {
    product_id: ProductId;
    total_qty: bigint;
    batches: Array<InventoryBatchPublic>;
}
export interface Category {
    id: CategoryId;
    owner: UserId;
    name: string;
    description: string;
}
export interface CategoryInput {
    name: string;
    description: string;
}
export interface PurchaseOrderInput {
    vendor: string;
    items: Array<PurchaseOrderItemInput>;
}
export type PurchaseOrderId = bigint;
export interface PurchaseOrderItem {
    product_id: ProductId;
    unit_cost: number;
    quantity: bigint;
    po_id: PurchaseOrderId;
}
export interface CartItem {
    product_id: ProductId;
    quantity: bigint;
    actual_sale_price: number;
}
export interface MonthlySalesTrend {
    month_label: string;
    total_revenue: number;
    total_volume_points: number;
}
export interface Sale {
    id: SaleId;
    owner: UserId;
    timestamp: Timestamp;
    total_revenue: number;
    total_volume_points: number;
    total_profit: number;
}
export interface DashboardStats {
    monthly_profit: number;
    total_inventory_value: number;
    recent_sales: Array<Sale>;
    monthly_volume_points: number;
}
export type BatchId = bigint;
export type UserId = Principal;
export interface PurchaseOrderItemInput {
    product_id: ProductId;
    unit_cost: number;
    quantity: bigint;
}
export type CategoryId = bigint;
export type SaleId = bigint;
export type ProductId = bigint;
export interface PurchaseOrder {
    id: PurchaseOrderId;
    status: POStatus;
    owner: UserId;
    vendor: string;
    timestamp: Timestamp;
}
export interface InventoryBatchPublic {
    id: BatchId;
    quantity_remaining: bigint;
    product_id: ProductId;
    unit_cost: number;
    date_received: Timestamp;
}
export interface ProfileInput {
    business_name: string;
    email: string;
    business_address: string;
    phone_number: string;
    fssai_number: string;
}
export interface SaleItem {
    unit_cost_snapshot: number;
    product_id: ProductId;
    product_name_snapshot: string;
    volume_points_snapshot: number;
    quantity: bigint;
    actual_sale_price: number;
    sale_id: SaleId;
    mrp_snapshot: number;
}
export interface Product {
    id: ProductId;
    mrp: number;
    sku: string;
    owner: UserId;
    name: string;
    earn_base: number;
    volume_points: number;
    hsn_code: string;
    category_id: CategoryId;
}
export enum POStatus {
    Received = "Received",
    Pending = "Pending"
}
export interface backendInterface {
    createCategory(input: CategoryInput): Promise<CategoryId>;
    createProduct(input: ProductInput): Promise<ProductId | null>;
    createPurchaseOrder(input: PurchaseOrderInput): Promise<PurchaseOrderId>;
    createSale(cartItems: Array<CartItem>): Promise<SaleId | null>;
    deleteCategory(id: CategoryId): Promise<boolean>;
    deleteProduct(id: ProductId): Promise<boolean>;
    getCategories(): Promise<Array<Category>>;
    getDashboardStats(): Promise<DashboardStats>;
    getInventoryBatches(product_id: ProductId): Promise<Array<InventoryBatchPublic>>;
    getInventoryLevels(): Promise<Array<InventoryLevel>>;
    getMonthlySalesTrend(): Promise<Array<MonthlySalesTrend>>;
    getProducts(): Promise<Array<Product>>;
    getProfile(): Promise<ProfileInput | null>;
    getPurchaseOrderItems(po_id: PurchaseOrderId): Promise<Array<PurchaseOrderItem>>;
    getPurchaseOrders(): Promise<Array<PurchaseOrder>>;
    getSale(sale_id: SaleId): Promise<Sale | null>;
    getSaleItems(sale_id: SaleId): Promise<Array<SaleItem>>;
    getSales(): Promise<Array<Sale>>;
    markPurchaseOrderReceived(po_id: PurchaseOrderId): Promise<boolean>;
    updateCategory(id: CategoryId, input: CategoryInput): Promise<boolean>;
    updateProduct(id: ProductId, input: ProductInput): Promise<boolean>;
    updateProfile(input: ProfileInput): Promise<boolean>;
}
import type { POStatus as _POStatus, ProductId as _ProductId, ProfileInput as _ProfileInput, PurchaseOrder as _PurchaseOrder, PurchaseOrderId as _PurchaseOrderId, Sale as _Sale, SaleId as _SaleId, Timestamp as _Timestamp, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createCategory(arg0: CategoryInput): Promise<CategoryId> {
        if (this.processError) {
            try {
                const result = await this.actor.createCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCategory(arg0);
            return result;
        }
    }
    async createProduct(arg0: ProductInput): Promise<ProductId | null> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPurchaseOrder(arg0: PurchaseOrderInput): Promise<PurchaseOrderId> {
        if (this.processError) {
            try {
                const result = await this.actor.createPurchaseOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPurchaseOrder(arg0);
            return result;
        }
    }
    async createSale(arg0: Array<CartItem>): Promise<SaleId | null> {
        if (this.processError) {
            try {
                const result = await this.actor.createSale(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSale(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteCategory(arg0: CategoryId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCategory(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: ProductId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategories();
            return result;
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getInventoryBatches(arg0: ProductId): Promise<Array<InventoryBatchPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventoryBatches(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventoryBatches(arg0);
            return result;
        }
    }
    async getInventoryLevels(): Promise<Array<InventoryLevel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventoryLevels();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventoryLevels();
            return result;
        }
    }
    async getMonthlySalesTrend(): Promise<Array<MonthlySalesTrend>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlySalesTrend();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlySalesTrend();
            return result;
        }
    }
    async getProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return result;
        }
    }
    async getProfile(): Promise<ProfileInput | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPurchaseOrderItems(arg0: PurchaseOrderId): Promise<Array<PurchaseOrderItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPurchaseOrderItems(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPurchaseOrderItems(arg0);
            return result;
        }
    }
    async getPurchaseOrders(): Promise<Array<PurchaseOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPurchaseOrders();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPurchaseOrders();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSale(arg0: SaleId): Promise<Sale | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSale(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSale(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSaleItems(arg0: SaleId): Promise<Array<SaleItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSaleItems(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSaleItems(arg0);
            return result;
        }
    }
    async getSales(): Promise<Array<Sale>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSales();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSales();
            return result;
        }
    }
    async markPurchaseOrderReceived(arg0: PurchaseOrderId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markPurchaseOrderReceived(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markPurchaseOrderReceived(arg0);
            return result;
        }
    }
    async updateCategory(arg0: CategoryId, arg1: CategoryInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCategory(arg0, arg1);
            return result;
        }
    }
    async updateProduct(arg0: ProductId, arg1: ProductInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1);
            return result;
        }
    }
    async updateProfile(arg0: ProfileInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0);
            return result;
        }
    }
}
function from_candid_POStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _POStatus): POStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_PurchaseOrder_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PurchaseOrder): PurchaseOrder {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProductId]): ProductId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SaleId]): SaleId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProfileInput]): ProfileInput | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Sale]): Sale | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PurchaseOrderId;
    status: _POStatus;
    owner: _UserId;
    vendor: string;
    timestamp: _Timestamp;
}): {
    id: PurchaseOrderId;
    status: POStatus;
    owner: UserId;
    vendor: string;
    timestamp: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_POStatus_n7(_uploadFile, _downloadFile, value.status),
        owner: value.owner,
        vendor: value.vendor,
        timestamp: value.timestamp
    };
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Received: null;
} | {
    Pending: null;
}): POStatus {
    return "Received" in value ? POStatus.Received : "Pending" in value ? POStatus.Pending : value;
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PurchaseOrder>): Array<PurchaseOrder> {
    return value.map((x)=>from_candid_PurchaseOrder_n5(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
